alibaba/BladeDISC

.gitmodules
SSH access is perfered because:
- Using the key is more secure than using a password
- No repetitive authentication is required as with HTTPS
=> [Chore] change submodules to ssh access

tao_compiler/mlir/disc/tests/regression/data/multi_threading_cpu_2d.mlir, tao_compiler/mlir/disc/tests/regression/data/multi_threading_cpu_3d.mlir, tao_compiler/mlir/disc/tests/regression/data/multi_threading_cpu_4d.mlir, tao_compiler/mlir/disc/tests/regression/multi_threading_cpu.cc, tao_compiler/mlir/xla/ral/context/common_context_impl.cc
For a nested parallel for loop:
```
scf.parallel((iv1, iv2, ... ivn) in range(L1, L2, ... LN)) {
...
}
```
The task assigner partitions the loop as even as possible across M threads.
Original implementation fails to tackle the situations like following example.
Suppose we have parallel domain: (5, 1) and 3 threads.
Original partition plan:
thread 0:
- task 0: (4:5, 0:1),
thread 1:
- task 0: (3:4, 0:1)
- task 1:  (4:5, 0:1)  # this is illegal
thread 2:
- task 0: (2:3, 0:1)
- task 1:  (4:5, 1:2) # this is illegal
This PR solve the above problem.
=> [disc-cpu] [bugfix] fix a bug of cpu multi-thread task assigner

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tests/regression/data/large_concat_cpu.mlir, tao_compiler/mlir/disc/tests/regression/data/large_concat_cpu_fused.mlir, tao_compiler/mlir/disc/tests/regression/large_concat.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/input_inline_fusion_pass.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
For a concat op:
```
lmhlo.concatenate(%operand1, %operand2, ... %operandN, %output) { concat_axis = m}
```
Original schedule:
```
scf.for ((iv1, ..., iv{m-1}, iv{m+1},...iv{n}) in  range(non_concat_dims)) {
scf.for (iv{m} in range(concat_dim)) {
if ((iv1, iv2, ..., ivn) maps to operand1) {
output[(iv1, iv2, ..., ivn)] = operand1[(iv1, ..., iv{m} - offset1, ...)];
} else if ((iv1, iv2, ..., ivn) maps to operand2) {
output[(iv1, iv2, ..., ivn)] = operand2[(iv1, ..., iv{m} - offset2, ...)];
} ... {
...
}
}
}
```
New schedule:
```
parallel.for %idx in range(num_operands_of_concat) {
if (%idx == 1) {
copy operand1 to output buffer
} else if (idx == 2) {
copy operand2 to output buffer
} ... {
...
} else {
copy the last operand to output buffer
}
}
```
=> [disc-cpu] add a new schedule for concat op with many operands

.gitmodules, tao/CMakeLists.txt
We use HTTP proxy in the internal cluster to fix random failed with `git clone, that the submodule should be HTTPS proto.
=> using https as submodule proto

pytorch_blade/src/compiler/mlir/converters/impl/convolution.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.cpp
Original implementation puts a conv op into the supported list of DISC
no matter what the input values/attributes of the conv op are. However,
we actually do not support transposed conv op a.t.m. This CL fix the
problem.
=> [torch converter][bugfix] Not convert transposed conv op

tao_compiler/mlir/disc/tests/mlir_feature_test.cc
Assign a unique test id for each feature test. We currently test both
`DISC_ENABLE_STITCH=true` and `DISC_ENABLE_STITCH=true` in the same
google test instance. Without this fix, these two tests will get same
name, leading to a very tricky error in the following pipeline.
=> fix broken test

tao_compiler/mlir/disc/transforms/codegen_utils.h, tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc
This provides a better row-reduction schedule speculation to increase ILP. Specifically, it decides to use more thread blocks when row-size is small and col-size is large enough.
=> Speculation strategy with better TLP for row-reduce.

tao_compiler/mlir/disc/tests/regression/corner_case.cc, tao_compiler/mlir/disc/tests/regression/data/corner_case_error_before_ptxas11100.mlir
Add a UT about PTXAS compilation error before version of 11.1. Incase we encounter the same error in a future PTXAS release.
=> UT for corner case of PTXAS error before v11.1.

tao_compiler/mlir/disc/transforms/disc_convert_const_to_ral.cc, tao_compiler/mlir/xla/ral/context/common_context_impl.cc, tao_compiler/mlir/xla/ral/context/common_context_impl.h, tao_compiler/mlir/xla/ral/context/common_context_impl_cuda.cc
This change is to fix the problem that huge splat constant may exceed the limit of protobuf.
=> Save const values in metadata.proto in splat mode

.github/workflows/main.yml, .gitmodules, docker/dev/Dockerfile.torch-disc, docker/scripts/install-pytorch-ltc.sh, pytorch_blade/src/BUILD, pytorch_blade/src/compiler/jit/BUILD, pytorch_blade/src/compiler/mlir/runtime/ral_context.cpp, scripts/ci/test_torch_disc.sh, torch_disc/.bazelrc, torch_disc/BUILD.bazel, torch_disc/README.md, torch_disc/WORKSPACE, torch_disc/bazel/torch/repo.bzl, torch_disc/bazel/torch/torch.BUILD.tpl, torch_disc/bazel_build.py, torch_disc/disc_demo.py, torch_disc/scripts/pytorch_patch.sh, torch_disc/setup.py, torch_disc/torch_disc/BUILD, torch_disc/torch_disc/csrc/init_python_bindings.cpp
This PR builds the TorchDISC pybind library  `_torch_disc.so` with Torch LTC, Torch Blade, and official PyTorch source code.
And also add a CI job to test it with a rough way: `import _torch_disc`.
The CI job includes two parts to reduce the CI time:
1. building devel docker: install PyTorch with `lazy_tensor_staging` branch from source code.
2. build and test torch-disc with the devel image from step1.
Develops can build from zero with the guide https://github.com/alibaba/BladeDISC/blob/de3a386114dfcd6038c16c9fbe0737c0a6c5f6ef/torch_disc/README.md
=> [TorchDISC] setup torch-disc building environment and CI job

.github/workflows/main.yml
always pull the latest devel Docker as the cache of devel docker building.
=> [CI] use the latest docker image as cache while building dev docker

pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_onnx_parser.cpp
We met segfault when retrieving error message after build engine failed. To make our process more robust we would like to enable log message only when TORCH_BLADE_DEBUG_LOG==on
=> [Torch] fix retrieve error message segfault

tao_compiler/mlir/disc/disc_compiler.cc
#227  To support JIT compilation on AArch64.  The default flag on AArch64 is static not PIC.
=> [AArch64] make sure PIC is used for jit compilation

tao/tao_bridge/passes/tao_encapsulate_subgraphs_pass.cc
`tao_compiler_main` failed to load graphdef with ops having `_output_shapes`. Just remote such attribute here as a workaround to fix such problem.
=> [bugfix] remove `_output_shapes` attr to avoid crash when loading graphdef to mlir

docker/dev/Dockerfile.aarch64, docker/runtime/Dockerfile.pytorch.aarch64, docker/runtime/Dockerfile.tf.aarch64, docker/scripts/install-python-aarch64.sh, scripts/ci/build_and_test.sh, scripts/ci/test_cpu_examples.sh, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp
We try to fix #244 in this PR. The root cause of the crash is still not clear. After doing some experiments, we think that it isn't likely to be the bug of BladeDISC itself.
- The crash could be re-produced on a graph with a single GEMM op using BladeDISC TF bridge.
- Same GEMM op test is ok if we do the test in UT environments (not using TF bridge) or use BladeDISC torch bridge.
-  Codegen kernel runs successfully using BladeDISC TF bridge.
-  if we use the wheel file from ARM community instead of `pip install tensorflow-aarch64`, GEMM op test is ok using BladeDISC TF bridge.
Thus, we provide a workaround to fix #244 by replacing the wheel package.
=> Fix cpu demo crash on aarch64 platform

pytorch_blade/src/compiler/jit/pybind_functions.cpp, pytorch_blade/src/compiler/jit/tool_funcs.cpp, pytorch_blade/src/compiler/jit/tool_funcs.h, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.cpp, pytorch_blade/tests/tensorrt/test_tensorrt.py, pytorch_blade/torch_blade/__init__.py, pytorch_blade/torch_blade/onnx_backends/backend_conversion.py, pytorch_blade/torch_blade/pass_manager.py, pytorch_blade/torch_blade/tensorrt/tensorrt_optimization.py
+ `torch._C._jit_pass_lower_to_onnx` and `torch._C._jit_pass_onnx_scalar_type_analysis` APIs has changed in torch 1.9.0 https://github.com/alibaba/BladeDISC/issues/253
+ Cast subgraph's inputs to `torch.int32` where it's `torch.int64` https://github.com/alibaba/BladeDISC/issues/254
TorchBlade returns a model with accuracy error, after optimizing the hugging face a pre-trained Albert model with TensorRT.
The script is listed as follow:
```python
import torch_blade
import torch_blade.tensorrt
from torch_blade.testing.common_utils import assert_almost_equal
from transformers import AlbertConfig, AlbertModel, AutoTokenizer
def load_albert_and_inputs():
model_name = "albert-base-v2"
model = AlbertModel.from_pretrained(model_name, torchscript=True).cuda()
tokenizer = …
```
=> [Torch] fixup onnx2trt int64 inputs

pytorch_blade/src/compiler/backends/backend_input_outputs.cpp, pytorch_blade/src/compiler/backends/backend_input_outputs.h, pytorch_blade/src/compiler/backends/engine_class.cpp, pytorch_blade/src/compiler/backends/engine_class.h, pytorch_blade/src/compiler/backends/engine_interface.cpp, pytorch_blade/src/compiler/backends/engine_interface.h, pytorch_blade/src/compiler/jit/fusion.cpp, pytorch_blade/src/compiler/jit/onnx_funcs.cpp, pytorch_blade/src/compiler/jit/shape_type_spec.cpp, pytorch_blade/src/compiler/jit/shape_type_spec.h, pytorch_blade/src/compiler/jit/shape_type_test.cpp, pytorch_blade/src/compiler/jit/tool_funcs.cpp, pytorch_blade/src/compiler/mlir/converters/impl/element_wise_binary.cpp, pytorch_blade/src/compiler/mlir/converters/impl/element_wise_unary.cpp, pytorch_blade/src/compiler/mlir/converters/impl/gru_cell.cpp, pytorch_blade/src/compiler/mlir/converters/impl/shapes.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_converter_register_test.cpp, pytorch_blade/src/compiler/mlir/runtime/disc_engine.cpp, pytorch_blade/src/compiler/mlir/runtime/disc_engine.h, pytorch_blade/src/compiler/mlir/runtime/ral_context.cpp, pytorch_blade/src/compiler/mlir/runtime/ral_context.h, pytorch_blade/src/compiler/tensorrt/tensorrt_engine.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.h, pytorch_blade/src/platform_alibaba, pytorch_blade/src/pybind.cpp
The inclusion of TorchScript one-stop header will such as:
```
#include <torch/script.h>
```
will lead to dependencies on un-related header files that are not required.
This will increase the risk of symbol conflicts. Sometimes we will run into segfault and it's hard to reason about.
To make our source files' dependencies clear, the pull request uses as more specific headers as possible.
=> [Torch] slim header files inclusion

tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp
ACL NEGEMM itself supports weight pre-packing by default. Without this
PR, we create a new dnnl::matmul primitive for each matmul call, which
in turn creates a new NEGEMM object inside the primitive on aarch64.
We can not re-use the pre-packed weight from previous matmul call even
for the same matmul configuration since the NEGEMM is destroyed after
each matmul call. This RP tries to cache the matmul primitive across
matmul calls and thus can make use of the underlying pre-packed weight
for compatible matmul calls.
=> Support gemm pre-packing via onednn/acl on aarch64

tao_compiler/mlir/disc/disc_compiler_main.cc, tao_compiler/mlir/disc/tests/mlir_test.cc
After adding a set of variables for UTs, it results in OOM on some GPUs due to the lack of memory freeing. This PR frees the unused GPU memory for the UTs.
=> Release GPU memory after UT to prevent OOM, enhance error code message.

tao_compiler/mlir/disc/tests/mlir_feature_test.cc, tao_compiler/mlir/disc/tests/mlir_feature_test.h, tao_compiler/mlir/disc/tests/mlir_test.cc, tao_compiler/mlir/disc/tests/mlir_test.h, tao_compiler/mlir/disc/tests/regression/data/use_expect_output.mlir, tao_compiler/mlir/disc/tests/regression/use_expect_output.cc
Some UTs are not runnable by TF (e.g. some custom quantized op).
This PR supports to use a set of provided output values as golden.
=> Support using provided output values as golden

tao_compiler/mlir/xla/ral/BUILD, tao_compiler/mlir/xla/ral/context/common_context_impl_acl.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_acl.h, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
Most part of this PR is just copied from the corresponding ACL layer
implementations. we re-implement these layers to add thread safety
support.
=> thread safe acl conv and depthwise conv

tao_compiler/mlir/disc/transforms/disc_for_loop_unroll_interleave.cc
Without this revision, the return type of the lambda function is not
defined. This error should be raised at compile time. However, it seems
to be ok at compile time in some environments while leading to a very weird
behavior at runtime.
=> fix mismatch return types of a lambda function

.github/workflows/main.yml, .github/workflows/torch_cuda_reusable.yml
Before adding benchmark CI jobs mentioned in https://github.com/alibaba/BladeDISC/issues/450. It's better to make the CUDA CI workflow for PyTorch reusable.
=> [CI] make torch cuda ci config reusable

docker/runtime/Dockerfile.pytorch
Before the deploy docker building failed because of the installation of python3 on ubuntu20. And we want to use the daily built runtime docker images for the TorchBlade benchmark mentioned in #450
=> [CI] fix install python3 on ubuntu20

.github/workflows/cronjobs.yml
The cronjob runs too often, and the dummy cronjob is meanless.
=> Disable dummy cronjob

tao/tao_bridge/common.cc, tao/tao_bridge/common.h, tao/tao_bridge/common_test.cc, tao/tao_bridge/kernels/tao_compilation_cache.cc, tao/tao_bridge/kernels/tao_compilation_cache.h, tao/tao_bridge/mlir/mlir_executable.cc, tao/tao_bridge/tao_compilation_result.proto
Support load/store compilation cache on disk in disc TF plugin. Note that:
- we suppose the clustering result is stable across different process.
The above assumption may not always hold. Thus be careful when using this
feature. 
- We may have multiple instances of `TaoCompilationCache` if we have
multiple sessions in the same process. However there should be only one
instance of `PersistentCompliationCache` in order to get a stable result.
=> support compilation cache serialization in disc TF plugin

pytorch_blade/tests/tensorrt/test_optimize.py
1. when `allow_tracing` is `False` and the `model_inputs` is None, the trt engine will not be built and thus the test case is meaningless
2. use a smaller model instead of the resnet18 to speed up the test case.
=> speed up ut for trt optimization  and fix bug with no input to record shape

scripts/python/common_setup.py, scripts/python/tao_build.py, tensorflow_blade/workspace0.bzl, third_party/bazel/acl/acl.BUILD, third_party/bazel/acl/acl_yitian.patch, third_party/bazel/blade_disc_dnn_workspace.bzl, third_party/bazel/blade_disc_helper/blade_disc_helper_configure.bzl, third_party/bazel/blade_disc_helper/build_defs.bzl.tpl
1, add a new build option `target_cpu_arch` to make ACL target arch
configurable.
2, add a new ACL patch for YITIAN to enable BF16/int8 dot instruction
3, currently only works in TF bridge. Torch bridge will be supported in
the future.
=> [AArch64] make ACL target arch configurable

tao_compiler/mlir/disc/transforms/disc_shape_optimization.cc, tao_compiler/mlir/disc/transforms/dot_rewriter.cc, tao_compiler/mlir/disc/transforms/tests/dot_rewriter.mlir
This pull request is mainly to convert vector operands of DoGeneralOp into matrixes. Please focus on reviewing `dot_rewriter.cpp` since other TorchToMhlo conversions are modified just to make the unit tests reach the case of DotGeneral rewritten passes. All TorchToMhlo passes will be replaced by the upstream implementations from Torch-MLIR.
=> DoGeneralOp convert vector to matrix

.github/workflows/tf24_gpu.yml, docker/cronjobs/Dockerfile.dummy, docker/runtime/Dockerfile.pytorch, docker/runtime/Dockerfile.tf_blade
`nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04` seemed disappear from docker hub, tf 2.4 CI job affected, use `nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04`.
=> fix missing nvidia/cuda:11.0-xxx image

tao_compiler/mlir/disc/transforms/dot_rewriter.cc, tao_compiler/mlir/disc/transforms/tests/dot_rewriter.mlir
This PR fixed core dump while two `dot_general` ops have the same producer `transpose` op, the following Canonicalizer pass would remove the transpose op if no consumer.
=> [BugFix] fix core dump on DotRewriter pass

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/transforms/disc_convert_fake_quant_op.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-convert-fake-quant-op.mlir
An example is shown as following.
convert:
```
const -> fake_quant
\
input -> fake_quant -> gemm -> fake_quant ->
```
to
```
const -> quantize
\
input -> quantize -> quantized_gemm -> dequantize ->
```
=> [quantization] add a pass to convert fake_quant annotated IR

pytorch_blade/src/compiler/mlir/runtime/ral_context.h, tao_compiler/mlir/disc/tests/mlir_test.cc, tao_compiler/mlir/disc/transforms/disc_convert_const_to_ral.cc, tao_compiler/mlir/disc/transforms/tests/disc-const-to-ral.mlir, tao_compiler/mlir/xla/ral/context/common_context_impl.cc, tao_compiler/mlir/xla/ral/context/common_context_impl.h, tao_compiler/mlir/xla/ral/context/common_context_impl_cuda.cc
1, assign a unique index for each unique const value.
2, using the index to do fast lool up whenever possible at runtime.
=> improve the performance of const lookup in RAL

.github/workflows/cronjobs.yml, .github/workflows/pytorch110_aarch64.yml, .github/workflows/pytorch112_cpu.yml, .github/workflows/pytorch112_gpu.yml, .github/workflows/pytorch160_cpu.yml, .github/workflows/pytorch171_gpu.yml, .github/workflows/pytorch181_cpu.yml, .github/workflows/pytorch181_gpu.yml, .github/workflows/pytorch190_gpu.yml, .github/workflows/tf115_cpu.yml, .github/workflows/tf24_gpu.yml, .github/workflows/tf280_aarch64.yml, .github/workflows/torchbench.yml
As discussed in https://github.com/orgs/community/discussions/13454 , github schedule actions only support UTC now.
So change time to schedule jobs at midnight.
=> [CI] Ci time fix

tao_compiler/mlir/xla/ral/ral_context.cc, tao_compiler/mlir/xla/ral/ral_context.h
assign a unique ID to each thread, add use a thread local api_func map
to reduce the chance of lock conflict.
=> thread local api_func cache to reduce the chance of lock conflict

tao_compiler/mlir/disc/transforms/disc_transpose_simplifier.cc, tao_compiler/mlir/disc/transforms/tests/disc-transpose-simplifier.mlir
The PR fixed infinite conversions loops on optimizations of ResNets
=> [bugfix] using reverse transpose permutation in reverseIfOperandsAreConsistentTransposeOps

pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp
To fix mobilenet optimization in TorchBench
=> Add hardswish and hardsigmoid to white list

scripts/ci/test_pytorch_blade.sh
Thus we have to delete old caches, otherwise, we will run out of disk space. Because Bazel has no strategies to clean old caches. 
As Bazel documents suggested, this pull request manual deletes cache content exceeding 10 days from the local disk.
Ref: https://bazel.build/remote/caching#delete-remote-cache
=> Delete old content from the disk remote cache

tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
Add a new env to control weight pre-packing for GEMM ops. This enables more fine-grained configuration.
=> [cpu] add a knob for GEMM weight pre-packing

tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc, tensorflow_blade/workspace0.bzl, third_party/bazel/acl/acl_cpu_gemm_assembly_dispatch.patch, third_party/bazel/acl/acl_cpu_winograd_conv2d_kernel.patch, third_party/bazel/blade_disc_dnn_workspace.bzl
1, patch ACL to support parallel `conv.run(...)`
2, change DISC accordingly to enable the above feature.
=> [AArch64] re-use ACL conv operator instance for different threads

tao/tao_bridge/test/gpu/mlir/test_mlir_transpose.py, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/tests/tensorflow_ops/data/transpose_2d_s_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/transpose_3d_s_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/transpose.cc, tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/xla/ral/BUILD, tao_compiler/mlir/xla/ral/context/custom_library/dimensions.h, tao_compiler/mlir/xla/ral/context/custom_library/gpu_helper.h, tao_compiler/mlir/xla/ral/context/custom_library/tf_topk.cu.h, tao_compiler/mlir/xla/ral/context/custom_library/tf_transpose.cu.h, tao_compiler/mlir/xla/ral/context/custom_library/transpose.h, tao_compiler/mlir/xla/ral/context/custom_library/transpose_gpu.cu.cc, tao_compiler/mlir/xla/ral/context/transpose_impl.cc
This PR added a custom library call for the transpose2D operator, which calls the TF kernel instead of the disc code generator to get higher performance. 
I will improve the disc codegen to get higher performance with fusion with other elementwise operator.
benchmark between disc codegen and custom library call:
(6144x3072xf32) |  latency | compute throughput | memory throughput
-- | -- | -- | --
custom call | 340 ms | 39.29% | 87.84%
disc code gen  | 688 ms | 11.45 % | 72.11 %
=> add transpose library call

docker/cronjobs/Dockerfile.torch.bench
nsys 2022.2.1 not available now. Update and download it from oss instead.
=> Fix torchBench nsys problem

pytorch_blade/bazel_build.py
To fix errors like when input with correct arguments:
```
TypeError: graph_create_get_attr(): incompatible function arguments. The following argument types are supported:
1. (arg0: torch::jit::Graph, arg1: torch::jit::Value, arg2: str) -> torch::jit::Node
```
=> fix pybind11 abi

tao_compiler/mlir/disc/disc_compiler.cc
The stitch optimization has been proven to be effective and robust by the [torch benchmark](https://github.com/pai-disc/torchbenchmark/commits/main), thus turning on by default
=> Enable stitch optimization by default.

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tests/regression/data/embedding_column_d_3d_i64.mlir, tao_compiler/mlir/disc/tests/regression/embedding_column.cc, tao_compiler/mlir/disc/transforms/disc_dynamic_slice_converter.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/mhlo-dynamic-slice-convert.mlir
1. add a pass to convert `mhlo.dynamic_slice` with dynamic shape input to `mhlo.real_dynamic_slice`, we have encountered such `mhlo.dynamic_slice` in easy rec's models with sparse input 
3. add a regression test for sparse subgraph
=> Add a `mhlo.dynamice_slice` converter pass

tao_compiler/mlir/disc/transforms/disc_shape_optimization.cc, tao_compiler/mlir/disc/transforms/disc_shape_optimization_utils.cc, tao_compiler/mlir/disc/transforms/tests/disc-shape-optimization.mlir
* propagate shape related info. through arith::trunci op
* simplify pattern like: `dynamic_reshape(tensor<8xf32>, ...) ->
tensor<1x?xf32>` to `reshape<8xf32> -> tensor<1x8xf32>`
=> several shape related improvements

tao_compiler/mlir/disc/transforms/mhlo_mark_shape_calc.cc, tao_compiler/mlir/disc/transforms/tests/mhlo_mark_shape_calc_op.mlir
This pr is prepared for `mhlo_disc.where` op's fusion implementation as mentioned in #742 
`mhlo.disc` op will produce 2 outputs, the 2nd output is i64 tensor with single element
represent number of valid elements in the 1st output, this will be used to calc the final output
shape used for `mhlo.real_dynamic_slice`.
It is indeed a shape calculation, but where op should not be considered as shape calc op, it is more than that.
By marking it as shape calc op will cause `mhlo_disc.where` impossible to fuse in later fusion pass. Evenmore, the element-wise ops produces the input for `mhlo_disc.where` will be marked as shape calc ops, thus they also cannot be fused in later passes.
With changes from current pr, we can generate the following IR(no disc.shape_op attr for where op), which can be …
=> skip mark mhlo.where as shape calc op

tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/tests/pdll/data/qgemm_i8_per_channel.mlir, tao_compiler/mlir/disc/tests/pdll/data/qgemm_i8_per_channel.pdll, tao_compiler/mlir/disc/tests/pdll/data/simple_fused_add_mul.pdll, tao_compiler/mlir/disc/tests/pdll/qgemm.cc, tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc, tao_compiler/mlir/disc/transforms/disc_pdl_utils.cc, tao_compiler/mlir/disc/transforms/lower_tf.cc, tao_compiler/mlir/xla/ral/BUILD, tao_compiler/mlir/xla/ral/context/common_context_impl_pdll.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc, tao_compiler/mlir/xla/ral/context/pdll_util.cc, tao_compiler/mlir/xla/ral/context/pdll_util.h, tao_compiler/mlir/xla/ral/ral_context.cc, tao_compiler/mlir/xla/ral/ral_logging.h
1, support BoolAttr/IntegerAttr/FloatAttr/DenseElementsAttr. Add UTs for these attribute types as well.
2, add an E2E TF QGEMM UT based on PDLL. Currently it's disable by default. We'll eventually change to PDLL based method by default after we do more evalutations.
=> [pdll] support more attribute types and add an e2e tf qgemm demo

tao_compiler/mlir/xla/ral/context/custom_library/transpose_gpu.cu.cc
narrowing convertion in array initializer list is not allowed by c++11, make the casting explicitly to avoid compiliation error.
=> Explict type casting to avoid compilation error

scripts/python/tao_build.py, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/tools/disc-opt/disc-opt.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/PassDetail.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/legalize_lmhlo_fusion_to_linalg.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/passes.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/register_passes.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/legalize-lmhlo-fusion-to-linalg.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_passes.td
An example is shown as following. Convert from:
```
func.func @name(%A: memref<?x?xf32>, %B: memref<?x?xf32>, %C:
memref<?x?xf32>) {
"lmhlo.fusion"() ({
"lmhlo.dot_general"(%A, %B, %C) {...}
"lmhlo.terminator"() : () -> ()
})
return %arg3 : memref<?x?xf32>
}
```
to:
```
func.func @name(%A: tensor<?x?xf32>, %B: tensor<?x?xf32>, %C:
tensor<?x?xf32>) {
%0 = linalg.fill(...)
%1 = linalg.matmul(%A, %B, ...)
return %1 : tensor<?x?xf32>
}
```
=> [transform] legalize a lmhlo fusion op to linalg

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc
The PR https://github.com/alibaba/BladeDISC/pull/719 overrides the logic of enabling stitch fusion optimization, making it turned off by default. Fix it in this PR.
=> Fix the bug that stitch is not enabled by default.

tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/passes.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/rewrite_payload_ir_for_ral.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/rewrite-payload-ir-for-ral.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_passes.td, tao_compiler/mlir/disc/transforms/disc_assign_memory_space.cc, tao_compiler/mlir/disc/transforms/placement_utils.cc, tao_compiler/mlir/disc/transforms/placement_utils.h
=> [transform] make the transformed payload ir suitable for RAL

examples/PyTorch/Inference/CUDA/BERT/main.py, examples/PyTorch/Inference/CUDA/BERT/requirements.txt, examples/PyTorch/Inference/CUDA/BERT/test.sh, pytorch_blade/pytorch_blade/BUILD, pytorch_blade/pytorch_blade/compiler/jit/BUILD, pytorch_blade/pytorch_blade/compiler/jit/aten_custom_ops.cpp, pytorch_blade/pytorch_blade/compiler/jit/pybind_functions.cpp, pytorch_blade/pytorch_blade/compiler/jit/tool_funcs.cpp, pytorch_blade/pytorch_blade/compiler/jit/tool_funcs.h, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscDecomposeComplexOps.cpp, pytorch_blade/tests/test_tools.py, pytorch_blade/tests/torchscript/BUILD, pytorch_blade/torch_blade/clustering/support_group_conversion.py, pytorch_blade/torch_blade/pass_manager.py, pytorch_blade/torch_blade/utils.py
Related to https://github.com/alibaba/BladeDISC/issues/785
1. Fix Bert amp example type promotion fail
2. fix amp in place op type promotion after removing the mutations
Before the mutation remover pass removes in-place-mutation information:
```
graph(%x.1 : Tensor,
%y.1 : Tensor):
%7 : float = prim::Constant[value=2.]() # test.py:9:24
%z.1 : Tensor = aten::mul(%x.1, %y.1) # test.py:6:8
%a.1 : Tensor = aten::add_(%z.1, %y.1, %7) # test.py:9:8
%c.1 : Tensor = aten::add_(%a.1, %y.1, %7) # test.py:10:8
return (%c.1)
=== after mutation remover ====>
graph(%x.1 : Tensor,
%y.1 : Tensor):
%7 : float = prim::Constant[value=2.]() # test.py:9:24
%z.1 : Tensor = aten::mul(%x.1, %y.1) # test.py:6:8
%22 : Tensor = aten::add(%z.1, %y.1, %7) # test.py:9:8
%23 : Tensor = aten::add(%22, %y.1, %7) # …
```
=> Fix Bert amp example type promotion fail

scripts/python/common_setup.py
pytorch_blade created a symbolic link to common_setup.py which use os.path.abspath() to get absolute path for itself. This make get_source_root_dir() return incorrect path to the BladeDISC source root when building pytorch_blade.
=> Fix getting wrong source root path when building pytorch_blade

scripts/python/tao_build.py, tao_compiler/mlir/disc/tools/disc-opt/disc-opt.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtBase.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtDialect.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtDialect.h, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtInterfaces.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtInterfaces.h, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtInterfaces.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.h, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/tests/BUILD, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/tests/invalid_ops.mlir, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/tests/ops.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_dialect_interpreter.cc
=> [transform] add disc_linalg_ext::multi_level_pack op

pytorch_blade/torch_blade/clustering/support_fusion_algorithm.py, pytorch_blade/torch_blade/config.py
Current torch_blade cluster setting(`max_iter_count=10`) has risk of early stopping before cluster final convergence. In the case of bert-base with fakequant node, the number of fusion block is 62 when `max_iter_count=10` while the number is 7 when `max_iter_count=40`. This phenomenon drastically influence the latency.
This PR aims to prevent performance drop in some cases by adding env to set specific `max_iter_count` value. Clustering policy refinement is in TODO list.
=> add env to control torch-blade cluster iteration

scripts/python/common_setup.py
Data type of args are converted to str after loading, leading to problematic behavior in boolean expression.
=> fix common config save/load bug

pytorch_blade/tests/disc/pdl/pdll_files/gpu/dequant_gemm_quant.pdll, pytorch_blade/tests/disc/pdl/pdll_files/gpu/dequant_gemm_quant_bias_f32_quant.pdll, pytorch_blade/tests/disc/pdl/pdll_files/gpu/dequant_gemm_quant_bias_quant.pdll, pytorch_blade/tests/disc/pdl/test_e2e/test_quantization.py, pytorch_blade/tests/disc/testing_base.py, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/xla/ral/BUILD, tao_compiler/mlir/xla/ral/context/quantized_gpu_kernel_impl.cc, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
About this pr:
1. Use cublasLt int8 gemm bias fusion kernel when bladnn is off. Cache the cublasLt setting for each kernel. 
2. Choose the faster kernel between bladnn and cublasLt when bladnn is on.
3. Add new pdl for cublasLt on cuda 11.7 whose bias should be float32.The logics of cublasLt int8 gemm bias fusion vary with cuda version. For example, fused bias on cuda 11.3 should be int8 while it should be float on cuda 11.7.
4. Cache kernel internal scale to avoid host/device memory transaction.
=> [Quantization] Enable quantization on gpu without bladnn

tao_compiler/mlir/disc/disc_compiler.cc
The dot merging is not always beneficial. Thus add a flag to control whether to enable it.
=> Add flag to contol dot merging.

scripts/python/tao_build.py, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/tests/disc-transform/data/packed_matmul_nn_p_f32_large_schedule.mlir, tao_compiler/mlir/disc/tests/disc-transform/matmul.cc, tao_compiler/mlir/disc/tests/disc-transform/matmul_multithread.cc, tao_compiler/mlir/disc/tests/disc-transform/packed_matmul.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/passes.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_dialect_interpreter.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_passes.td, tao_compiler/mlir/disc/tools/disc-transform/utils.cc, tao_compiler/mlir/disc/tools/disc-transform/utils.h, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_transform_legalize_to_loop.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.h, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h
=> [transform] add a default schedule

tao_compiler/mlir/disc/transforms/disc_duplicate_computation_for_fusion.cc, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-lmhlo-fusion.mlir, tao_compiler/mlir/disc/transforms/tests/disc-duplicate-computation-for-fusion.mlir
1, not fuse a const op if there are external consumers.
2, add a pattern to duplicate const ops for dot ops to reduce the case where multiple dot ops share the same weight op while requiring different layout.
to #787
=> [transform] not allow const as the final output of fusion

tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/legalize_lmhlo_fusion_to_linalg.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/legalize-lmhlo-fusion-to-linalg.mlir, tao_compiler/mlir/disc/tools/disc-transform/utils.cc, tao_compiler/mlir/disc/tools/disc-transform/utils.h, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc
op type is not reliable in case there are multiple ops having the same type. This CL assigns a unique name for each op being transformed and build transform IR based on the name instead of op type. This will help to enable more complicated fusion pattern.
to #787
=> [transform] name each op and transfrom based on name instead of type

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/tests/regression/data/kstitch_fusion_elemwise_shm_cache_large.mlir, tao_compiler/mlir/disc/tests/regression/data/kstitch_fusion_elemwise_shm_cache_small.mlir, tao_compiler/mlir/disc/tests/regression/kstitch_fusion.cc, tao_compiler/mlir/disc/transforms/codegen_utils.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.cc, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.h, tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.cc, tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.h, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/passes.h
This PR uses shared memory to cached intermediate data of element-wise ops that could be reused across different stitch groups. It helps to reduce redundant computation and off-chip memory traffic. It requires that `DISC_MEM_INTENSIVE_OPT_EXPERIMENTAL=true`.
=> Using shared memory to cache element-wise results in stitch fusion.

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/convert_foreach_thread_op_to_parallel_op.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/passes.h, tao_compiler/mlir/disc/tools/disc-transform/transforms/rewrite_payload_ir_for_ral.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/convert-foreach-thread-to-parallel.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_passes.td, tao_compiler/mlir/disc/transforms/disc_outline_cpu_kernel.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc
single iteration `scf.parallel` op will be removed, making the outline cpu kernel pass failed to outline transform based codegen kernel (we only support single thread a.t.m.). This PR convert foreach thread op to parallel op right before output cpu kernel pass to avoid it's being removed.
to #787
=> [transform] convert foreach thread op to parallel right before outline cpu kernel

tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-lmhlo-fusion.mlir
=> [transform] enhance fusion pass to support epilogue fusion

pytorch_blade/tests/test_passes.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/exporter.py, pytorch_blade/torch_blade/pass_manager.py
In some case, a model may be exported with multiple devices. While for inference, only a single device is required. This option is to force all constant on all CUDA devices to the specified one.
It is potentially unsafe, just like `enable_force_to_cuda`, and should be used with care.
=> Add config option to force multiple cuda devices into a single one

tao/tao_bridge/passes/tao_mark_for_compilation_pass.cc, tao/tao_bridge/tf/xla_op_registry.cc, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/IR/hlo_disc_enums.td, tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/IR/lhlo_disc_enums.td, tao_compiler/mlir/disc/IR/lhlo_disc_ops.cc, tao_compiler/mlir/disc/IR/lhlo_disc_ops.h, tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/IR/tests/invalid_hlo_disc.mlir, tao_compiler/mlir/disc/IR/tests/ops_hlo_disc.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sparse_segment_sum_d_f32_2d.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sparse_segment_sum_p_f64_2d.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sparse_segment_sum_s_f32_2d.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/sparse_segment_sum.cc, tao_compiler/mlir/disc/transforms/disc_hlo_legalize_to_lhlo.cc, tao_compiler/mlir/disc/transforms/disc_map_hlo_to_lhlo_op.h, tao_compiler/mlir/disc/transforms/fusion_utils_sparse_op_cpu.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/lower_tf.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-sparse-segment-mean-lhlo-legalize-roots-to-loops.mlir, tao_compiler/mlir/disc/transforms/tests/cpu-only-sparse-segment-reduction-lhlo-legalize-roots-to-loops.mlir
1. refactor mhlo_disc/lmhlo_disc's `SparseSegmentMean` to `SparseSegmentReduction` with `is_mean` attr to support both tf.sparse_segment_mean and tf.sparse_segment_sum
2. refactor codegen logic, replace impl with `scf.for` to `scf.parallel` for possible fusion
3. support clustering for tf.sparse_segment_sum in tao bridge
4. refine UTs to adapt to code changes
=> refactor: add sparse_segment_reduction to support both sparse_segment_mean/sum

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/reduction-input-fuse.mlir
=> [transform] add reduction_input_fuse primitive

tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
Without this PR, stream executor (se) will call
`cudnnGetConvolutionForwardWorkspaceSize` everytime. This cudnn api itself is very time-consuming on cuda platform, leading to e2e performance regression for cnn networks (e.g. resnet). In this PR, we choose to cache such config to reduce the overhead.
some performance number of testing resnet50 with batch size 32 on A100:
```
|    | Backend     |   batch | precision   |   Median(FPS) |   Mean(FPS) |   Median(ms) |   Mean(ms) |     99th_p |     std_dev |
|---:|:------------|--------:|:------------|--------------:|------------:|-------------:|-----------:|-----------:|------------:|
|  0 | eager       |      32 | fp32        |       2652.74 |     2634.96 |   0.012063   | 0.0121528  | 0.0134366  | 0.000334012 |
|  1 | script      |      32 | …
```
=> bugfix: fix se conv kernel performance regression

examples/PyTorch/Inference/hf_transformers/blade_adapter.py, examples/PyTorch/Inference/hf_transformers/tests/test_optimize.py, examples/PyTorch/Inference/hf_transformers/tests/test_pipeline.py, examples/PyTorch/Inference/hf_transformers/tests/test_trace_model.py, examples/PyTorch/Inference/hf_transformers/tests/test_wrapper_model.py
Refactor huggingface transformer adapter to support decoder-only generation pipeline (e.g. text-generation with gpt2):
- programmatically create wrapper class (inherited from original hf transfromers model class) to keep generation related methods (e.g. prepare_inputs_for_generation).
- specify default forward kwargs (e.g. use_cache) so we can torch.jit.trace model correctly.
- add some unit tests.
Some TODOs (will be implemented in future PRs):
- support use_cache=True for decoder-only model
- support encoder-decoder generation model (e.g. bart, t5)
=> Support decoder-only generation in hf transformers adapter.

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/tests/disc-transform/matmul_epilogue.cc, tao_compiler/mlir/disc/tools/disc-opt/disc-opt.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.h, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/decompose-vectors.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/disc-bufferize.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/lower-conditional-generic.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_dialect_interpreter.cc, tao_compiler/mlir/disc/transforms/disc_duplicate_computation_after_fusion.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-duplicate-computation-after-fusion.mlir
to #787 
1, decompose scf.if with result having large vector size
2, work around inefficent lower code of arith.select with vector type
3, work around split vector xfer op into full and partial inside a if op.
4, vector.extract_strided_slice/extrac and
vector.insert/vector.insert_strided_slice pair elimination
5, add a pass to duplicate and fuse some computations into the consumer fusion op in order to remove memory footprint
6, use tile buffer to stitch gemm computation and the following epilogue computation by default instead of using vector register. We found that when the epilogue computaion has many operands (except from the gemm), the l1/l2 cache will be polluted by these operands, which significantly hurts the performance of the gemm.
=> [transform] some optimization for split-k gemm epilogue fusion

pytorch_blade/scripts/build_pytorch_blade.sh
some enviroment problem block torch1.12+cu113 CI build, like https://github.com/alibaba/BladeDISC/actions/runs/4418340044/jobs/7745328856 . Disable it momentarily.
=> [CI] disable LTC in build script

tools/torch_quant/tests/test_quantizer.py, tools/torch_quant/torch_quant/quantizer.py
1. modify fbgemm default activation observer type, change to HistogramObserver;
2. remove unused modules after quantization to avoid possible tracing errors.
=> [torch-quant] modify fbgemm default activation observer type

tools/torch_quant/tests/test_quantizer.py, tools/torch_quant/torch_quant/graph.py, tools/torch_quant/torch_quant/quantizer.py
[torch-quant] update weight observer qscheme before converting to ref, change symmetric to affine
=> [torch-quant] update weight observer qscheme before converting to ref

.github/workflows/pytorch200_cpu.yml, .github/workflows/pytorch200_gpu.yml, pytorch_blade/benchmark/TorchBench/requirements_cpu.txt, pytorch_blade/benchmark/TorchBench/requirements_cuda.txt, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/scripts/pip/requirements-dev-2.0.0+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-2.0.0+cu117.txt, pytorch_blade/scripts/pip/requirements-dev-pre+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-pre+cu117.txt, pytorch_blade/torch_blade/dynamo/__init__.py, pytorch_blade/torch_blade/testing/common_utils.py
PT2 had been released https://pytorch.org/blog/new-library-updates-in-pytorch-2.0/
Co-author: @zhangxiao-stack has fix PT2 compile in PR https://github.com/alibaba/BladeDISC/pull/1069
=> Update PT2 wheels

tao_compiler/mlir/disc/transforms/disc_shape_optimization.cc, tao_compiler/mlir/disc/transforms/disc_shape_optimization_utils.cc
refator the production equality propagation part of shape optimization pass.
The time of `LowerHLOToLLVM` for GTP-2 model decreases from ~850s (w/o weight freeze) to ~620s
=> compilation time optimization round 1

pytorch_blade/tests/test_config.py, pytorch_blade/torch_blade/clustering/support_group_conversion.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/mlir/disc_engine_conversion.py
multi-cc compilation will take longer time. Add flag to control it.
Disable it will reduce the compilation time for `GpuKernelToBlobPass` from ~200s to ~80s.
=> add flag to control multi-cc compilation

tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_stitch_gpu.cc, tao_compiler/tao
mixing col reduction in row reduction fusion block caused a bug on indexing, this PR avoid mixing row/col into one fusion block.
=> avoid mix reduction type in one fusion block

pytorch_blade/pytorch_blade/compiler/jit/pybind_functions.cpp, pytorch_blade/tests/disc/test_cache.py, pytorch_blade/torch_blade/logging.py, pytorch_blade/torch_blade/mlir/cache.py, pytorch_blade/torch_blade/mlir/disc_engine_conversion.py, pytorch_blade/torch_blade/mlir/hash.py
This PR allowed pytorch_blade to cache the compilation result on JIT or AOT compilation progress.
Uses can enable this feature using env `TORCH_BLADE_ENABLE_COMPLATION_CACHE=true`.
=> add torch_blade compilation cache

pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp
this PR added a env to filter torch white list with `export TORCH_MHLO_OP_BLACK_LIST="xxxx"`, this flag can help developers to debug.
=> add black list to filer torch ops

pytorch_blade/torch_blade/context.py
this PR add a `torch_blade.disc_context` module to fetch compilation context, an example to confirm disc works well please go to  https://github.com/pai-disc/aicompiler/pull/16/files#diff-1e0d1d33580e119b4ed6cf6c87c4b3c935eba19ea871e5c28abe5fcdcb94cdaf
=> add disc_context_guard to fetch compilation context

tao_compiler/mlir/disc/disc_compiler.cc
We encounter some models whose generated kernels suffer from index overflow due to the i32 data type. With this commit, by using the environment `DISC_CODEGEN_INDEX_BITWIDTH=64`, the codegen will use i64 for index computation. We may also need to update the index type selection logic on the CPU side someday.
=> Add environment to enable using i64 for GPU index computation.

pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/MhloPasses.cpp
After `createDecomposeComplexOpsPass`, the `torch.aten.linear` will be decomposed to `matmul` with the weight transformed from `nxk` to` kxn`, which is more friendly for weight-only quantization pattern match.
=> enable pdl pattern match in more place

pytorch_blade/pytorch_blade/compiler/jit/fusion.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/MhloPasses.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/TorchToMhlo/DiscTorchToMhlo.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/ApplyValueSemantics.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscConvertTorchToDiscMhlo.cpp, pytorch_blade/tests/disc/ops/test_input_mutation.py, pytorch_blade/tests/mhlo/BUILD, pytorch_blade/tests/mhlo/custom_fake_quant.mlir, pytorch_blade/torch_blade/dynamo/__init__.py, tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/transforms/disc_hlo_legalize_to_lhlo.cc, tao_compiler/mlir/disc/transforms/disc_lhlo_rewriter.cc, tao_compiler/mlir/disc/transforms/tests/input-mutation.mlir
=> using args-mutation annotation to support inplace op in torch-blade pipline

tao_compiler/mlir/ral/context/stream_executor_based_impl.cc
Instead of hard-coding 256M for the scratch memory limit, introduce environment TAO_SCRATCH_ALLOC_LIMIT_BYTES to set it.
=> Support setting scratch memory limit by env

pytorch_blade/pytorch_blade/BUILD, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/disc_ops/BUILD, pytorch_blade/pytorch_blade/disc_ops/attention_op.cpp, pytorch_blade/tests/torch-disc-ops/test_attention_op.py
This PR added a PyTorch custom operator `disc::attentionF` op schema, that we can use pdll to lower this op to disc BladNN custom call .
=> add DISC attentionF custom operator schema

pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/pytorch_blade/compiler/mlir/runtime/ral_context.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/TorchToMhlo/DiscTorchToMhlo.cpp, pytorch_blade/tests/disc/ops/test_input_mutation.py, pytorch_blade/torch_blade/pass_manager.py, tao_compiler/mlir/disc/transforms/codegen_utils.cc, tao_compiler/mlir/disc/transforms/disc_lhlo_rewriter.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.cc, tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
related tf pr: https://github.com/pai-disc/tensorflow/pull/33
this PR run throught inplace KV cache compilation pipeline in torch_blade inference API, which includes 3 parts:
1. add re-inplace pass on PyTorch IR to re-inplace on mutation node, such as slice->add_ will be transformed into slice->add->slice_scatter.
2. implement `mhlo.dynamic_update_slice` operator code generator with some performance improvement
=> run through inplace KV cache compilation pass pipeline in torch_blade

docker/scripts/install-python.sh, pytorch_blade/scripts/pip/requirements-dev-1.13.1+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-1.13.1+cu116.txt, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/transforms/disc_input_output_alias.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-input-output-alias.mlir
In this pr, we provide a mechanism to do memory buffer reuse optimization between module inputs and outputs. Frontend of DISC needs to provide information as module attribute in the form of `input_output_alias_params` and `input_output_alias_outputs`. For example, if you want to reuse the 3rd output tensor and 14th input tensor, 4th output tensor and 2nd input tensor of main module function, you need to provide these two attributes like:
```
input_output_alias_params="14,2"
input_output_alias_outputs="3,4"
```
DISC will parse this information and try to do buffer reuse.
It should be noted that DISC's handling of input_output_alias information adopts a try-best strategy, which means that it does not guarantee the successful execution of all input-output aliases, but this does not affect …
=> Add pass to process input and output alias hint info

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_reduce_buffer_live_range.cc, tao_compiler/mlir/disc/transforms/passes.h
the reduce-buffer-live-range pass moves the `AllocOp` to the nearest location to the consumer to avoid early allocation to reduce memory peak.
=> add reduce-buffer-live-range pass to reduce memory peak

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/transforms/disc_collective_ops_rewriter.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/mhlo_decomp_rewriters.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-collective-ops-rewriter.mlir, tao_compiler/mlir/disc/transforms/tests/mhlo_decomp_rewriter.mlir, tao_compiler/mlir/ral/collective.cu.cc
add DiscCollectiveOpsPass to rewriter mhlo collective ops into disc custom library call.
=> Add DiscCollectiveOpsPass and related collective ops

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/transforms/disc_argsmutation_expand.cc, tao_compiler/mlir/disc/transforms/disc_input_output_alias.cc, tao_compiler/mlir/disc/transforms/disc_lhlo_rewriter.cc, tao_compiler/mlir/disc/transforms/mhlo_disc_passes.td, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/input-mutation.mlir
The key is to expand `args_mutation` op before GPU code-gen.
=> Optimize input-output alias

tao_compiler/decoupling/mlir_compiler.cc, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tools/disc-opt/disc-opt.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_shape_propagate.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-shape-propagate.mlir
```python
import torch
import torch.nn as nn
import unittest
import torch_xla.core.xla_model as xm
import torch.nn.functional as F
torch.manual_seed(1001)
xla_device = xm.xla_device()
#xla_device = "cuda"
dtype = torch.float16
class TestMLP(nn.Module):
def __init__(self):
super(TestMLP, self).__init__()
self.fc = nn.Linear(1024, 4096, bias=False)
def forward(self, x):
return self.fc(x)
class TestDynamicShape(unittest.TestCase):
def test_embeded(self):
device = xla_device
m = TestMLP().to(device)
m.train()
with torch.cuda.amp.autocast(dtype=torch.bfloat16):
for i in range(10):
xla_tensor = torch.rand(i+1, 1024, requires_grad=False)
xla_tensor = xla_tensor.to(device)
xla_output = m(xla_tensor)
loss = xla_output.sum()
loss.backward()
xm.mark_step()
print(f"iteration :{i}, loss: …
```
=> add shape propagate pass on mhlo

tao_compiler/mlir/disc/transforms/disc_shape_propagate.cc, tao_compiler/mlir/disc/transforms/tests/disc-shape-propagate.mlir
=> Support shape_propagate for more ops
