alibaba/BladeDISC

.github/workflows/main.yml
=> [CI] update trigger policy

pytorch_blade/.gitignore
Update torch_addons to pytorch_blade in .gitignore
=> Update to pytorch_blade in .gitignore

.github/workflows/main.yml
The deployment job can not be triggered as expected, this PR fixed this issue.
=> Update deploy job branch ref

docs/developers/pass_pipeline.md
=> Add pass_pipeline.md

.github/workflows/main.yml, docs/install_with_docker.md, scripts/ci/deploy_tf_wrapper.sh
This PR adds a document to introduce how to install BladeDISC with Docker, that all tutorials can reference this document.
=> install BladeDISC with Docker

.github/workflows/main.yml
=> fix pre-commit failed on CI

README.md, docs/developers/pass_pipeline.md, docs/developers/runtime_abstraction_layer.md, pytorch_blade/src/compiler/mlir/converters/impl/convolution.cpp
- [Torch] tiny spelling fix
- [Torch] fix deprecated aten::_convolution
=> [Torch] fix deprecated aten::_convolution

.github/workflows/main.yml, tao_compiler/mlir/disc/transforms/disc_outline_cpu_kernel.cc
=> [disc-cpu] fix #54 and re-enable CPU ci test

mhlo_builder/mlir/mhlo/builder/standard.cpp, mhlo_builder/mlir/mhlo/builder/standard.h, pytorch_blade/src/compiler/mlir/converters/impl/activation.cpp, pytorch_blade/tests/mlir/test_disc_activation.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/exporter.py
Address https://github.com/alibaba/BladeDISC/issues/42
=> [Torch] Add hardtanh and custom jit pass

tao_compiler/mlir/disc/tests/tensorflow_ops/data/pad_d_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/pad_p_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/pad_s_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/pad.cc
The associate tf_community change:
https://github.com/pai-disc/tensorflow/commit/9f534cd877104d214fac87f9b3437b933c3e9d52
=> Update tf_community to fix a bug of tf.PadV2 lowering

mhlo_builder/mlir/mhlo/builder/standard.cpp, mhlo_builder/mlir/mhlo/builder/standard.h, pytorch_blade/src/compiler/mlir/converters/impl/list_operations.cpp, pytorch_blade/src/compiler/mlir/converters/impl/tensor.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.cpp, pytorch_blade/tests/mlir/test_disc_list.py, pytorch_blade/tests/mlir/test_disc_tensor.py, pytorch_blade/torch_blade/mlir/disc_engine_conversion.py, tao_compiler/mlir/disc/transforms/mhlo_mark_shape_calc.cc
+ prim::ListUnpack
+ prim::NumToTensor
+ aten::Int
=> [Torch] Add torch2mhlo operations

tao_compiler/mlir/disc/transforms/disc_shape_simplifier.cc
Enhance the conversion from "ExpandDim - DynamicBroadcastInDim" to DynamicBroadcastInDim.
=> ExpandDim-DynamicBroadcastInDim simplifier enhancement.

docs/build_from_source.md
=> [docs] add CPU support in build_from_source.md

tao_compiler/mlir/disc/tests/tensorflow_ops/range.cc
tf_community change:
https://github.com/pai-disc/tensorflow/commit/6f3b0aad7eed51ef4897d50201cfb169f66a3c2d
=> [tf2mhlo] support tf.Range with negative stride

tao/tao_bridge/kernels/launch_base.cc
Take host args into consideration as well when calculating the start
offset of resource args.
=> [bugfix][bridge] fix wrong start offset of resource args

tao_compiler/mlir/disc/tests/tensorflow_ops/data/strided_slice_with_newaxis_d_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/strided_slice.cc
tf_community related change:
https://github.com/pai-disc/tensorflow/commit/3653a3532266c7877a6148a9007a5cde9eeb10ba
=> [tf2mhlo] support tf.StridedSlice with new_axis_mask

tao_compiler/mlir/disc/transforms/tests/mhlo-canonicalizer.mlir
The associated change in tf_community: https://github.com/pai-disc/tensorflow/commit/2a45e96c28b2b6434ee199d59bec6e23bff4a3dd
=> Update tf_community to add two canonicalization patterns

tao/tao_bridge/passes/tao_mark_for_compilation_pass.cc, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sqrt_d_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sqrt_p_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/sqrt_s_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/sqrt.cc
Add tests for tf.Sqrt as well. We already have tests for tf.Softplus.
=> [bridge] support tf.Sqrt and tf.Softplus

tao_compiler/mlir/disc/transforms/shape_utils.cc
This helps to propagate more possible static information. The simplifier pass appears before dot-converter pass, and thus we need to support DotOp.
=> Add shape constraint for mhlo::DotOp.

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tests/regression/data/kstitch_fusion_with_splat_const.mlir, tao_compiler/mlir/disc/tests/regression/kstitch_fusion.cc, tao_compiler/mlir/disc/transforms/disc_fuse_splat_const.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-fuse-splat-const.mlir
Add FuseSplatConstPass to support fusion of splat const to avoid unnecessary memory access #113
=> Add FuseSplatConstPass to support fusion of splat const to avoid

tao/tools/download_protoc.sh
=> Add alicloud URL to download protoc

pytorch_blade/.bazelrc, pytorch_blade/ci_build/build_pytorch_blade.sh, pytorch_blade/src/compiler/backends/backend_input_outputs.cpp, pytorch_blade/src/compiler/backends/backend_input_outputs.h, pytorch_blade/src/compiler/backends/engine_class.cpp, pytorch_blade/src/compiler/backends/engine_interface.h, pytorch_blade/src/compiler/mlir/converters/impl/shapes.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_logger.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_onnx_parser.cpp, pytorch_blade/src/compiler/tensorrt/pybind_functions.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.h, pytorch_blade/src/pybind.cpp, pytorch_blade/tests/mlir/test_disc_reduction.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/onnx_backends/backend_conversion.py, pytorch_blade/torch_blade/onnx_backends/backend_testbed.py, pytorch_blade/torch_blade/pass_manager.py, pytorch_blade/torch_blade/tensorrt/dynamic_shapes.py, pytorch_blade/torch_blade/utils.py
A fork of #177, but disable remote cache.
=> [Torch] improve TensorRT fallback & dynamic

.github/workflows/main.yml, .github/workflows/ngc_reusable.yml, docker/dev/Dockerfile.torch.ngc, docker/scripts/ubuntu20.04.list, pytorch_blade/.gitignore, pytorch_blade/benchmark/detectron2/run_blade.py, pytorch_blade/benchmark/detectron2/test_d2_benchmark.sh, pytorch_blade/benchmark/requirements.txt, pytorch_blade/benchmark/run_benchmark.sh, pytorch_blade/benchmark/torch-tensorrt/config/crnn.yml, pytorch_blade/benchmark/torch-tensorrt/config/vgg16.yml, pytorch_blade/benchmark/torch-tensorrt/config/yolov5.yml, pytorch_blade/benchmark/torch-tensorrt/perf_run.py, pytorch_blade/benchmark/torch-tensorrt/test_trt_benchmark.sh, pytorch_blade/requirements-dev-ngc.txt, scripts/ci/deploy_pytorch_blade.sh, scripts/ci/test_pytorch_blade.sh
Related to https://github.com/alibaba/BladeDISC/issues/157
=> [Torch] Add benchmark for ONNX-TensorRT

.github/workflows/main.yml, docker/runtime/Dockerfile.tf_blade, docker/scripts/install-tensorrt.sh, scripts/ci/deploy_tensorflow_blade.sh, scripts/ci/test_tensorflow_blade.sh, tensorflow_blade/BUILD, tensorflow_blade/build.py, tensorflow_blade/build_pip_package.sh, tensorflow_blade/setup.py, tensorflow_blade/src/tensorrt/BUILD, tensorflow_blade/src/tensorrt/bridge/tensorrt_logger.cpp, tensorflow_blade/tf_blade/gpu/tf_to_trt.py, tensorflow_blade/tf_blade/util/tf_conversion_util.py, tensorflow_blade/version.py, third_party/bazel/blade_helper/build_defs.bzl.tpl, third_party/bazel/tensorrt/trt.BUILD.tpl
@qiuxiafei @Yancey1989 @linearhit 
I think we need to discuss whether we need to maintain a separated runtime docker image for tensorflow blade or should install tensorflow-blade in our current tf runtime images.
Since currently the ci action for tensorflow-blade does not build disc for tensorflow, maybe a separated docker image is good for now.
=> [Tensorflow] [to #195] package tensorflow wheel and deploy a runtime docker

.github/workflows/main.yml, pytorch_blade/src/BUILD, pytorch_blade/src/common_utils/BUILD, pytorch_blade/src/common_utils/logging.h, pytorch_blade/src/common_utils/tempfs.cpp, pytorch_blade/src/common_utils/utils.cpp, pytorch_blade/src/common_utils/utils.h, pytorch_blade/src/compiler/backends/engine_class.cpp, pytorch_blade/src/compiler/jit/pybind_functions.cpp, pytorch_blade/src/compiler/mlir/converters/BUILD, pytorch_blade/src/compiler/mlir/converters/impl/element_wise_binary.cpp, pytorch_blade/src/compiler/mlir/converters/impl/layernorm.cpp, pytorch_blade/src/compiler/mlir/converters/impl/reduction.cpp, pytorch_blade/src/compiler/mlir/converters/impl/shapes.cpp, pytorch_blade/src/compiler/mlir/converters/impl/softmax.cpp, pytorch_blade/src/compiler/mlir/converters/impl/tensor.cpp, pytorch_blade/src/compiler/mlir/converters/impl/utils.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_converter_register.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_logger.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_onnx_parser.cpp, pytorch_blade/src/compiler/tensorrt/tensorrt_engine_context.cpp, pytorch_blade/torch_blade/logging.py, pytorch_blade/torch_blade/mlir/disc_engine_conversion.py
1. Change logging to tf logging
2. Add read environments variables utilities
3. CMake build will be broken. To unlock the ci, we will disable TorchBlade CMake CI, since it will be deprecated soon.
=> [Torch] refactor logging and debug tools

pytorch_blade/.mdl_style.rb, pytorch_blade/.mdlrc, pytorch_blade/README.md, pytorch_blade/benchmark/README.md, pytorch_blade/benchmark/detectron2/README.md, pytorch_blade/benchmark/detectron2/run_blade.py, pytorch_blade/benchmark/detectron2/test_d2_benchmark.sh, pytorch_blade/benchmark/run_benchmark.sh, pytorch_blade/benchmark/torch-tensorrt/README.md, pytorch_blade/benchmark/torch-tensorrt/config/yolov5.yml, pytorch_blade/benchmark/torch-tensorrt/perf_run.py, pytorch_blade/benchmark/torch-tensorrt/test_trt_benchmark.sh
The pull request adds the following:
1. Tutorials and readme to the benchmark
2. List some test results
3. Update warmup and run_iterations in torch-tensorrt/perf_run.py
=> [Torch] TensorRT benchmark

tensorflow_blade/build.py, third_party/bazel/blade_helper/blade_helper_configure.bzl, third_party/bazel/blade_helper/build_defs.bzl.tpl, third_party/bazel/cuda_static/build_defs.bzl.tpl, third_party/bazel/cuda_static/cuda_static.BUILD.tpl, third_party/bazel/cuda_static/cuda_static_configure.bzl, third_party/bazel/tf/build_defs.bzl.tpl, third_party/bazel/tf/tf_configure.bzl
Make the internal code share bazel rules from open source repo
Currently works for tensorflow-gpu==2.4.0, need more test.
=> adapt for internal blade build

tao_compiler/mlir/disc/transforms/disc_dot_merge.cc, tao_compiler/mlir/disc/transforms/tests/disc-dot-merge.mlir
Merge Several DotGeneralOp with same one-side operand together.
=> DotOp merge optimization.

pytorch_blade/bazel_build.py, pytorch_blade/distribution.cfg, pytorch_blade/src/BUILD, pytorch_blade/src/compiler/backends/engine_class.h, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_common.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_common.h, third_party/bazel/tensorrt/trt.BUILD.tpl
=> [Torch] standalone pure c/c++ libtorch_blade.so

.github/workflows/main.yml, docker/dev/Dockerfile.aarch64, docker/runtime/Dockerfile.pytorch.aarch64, docker/runtime/Dockerfile.tf.aarch64, pytorch_blade/.bazelrc, pytorch_blade/WORKSPACE, pytorch_blade/ci_build/build_pytorch_blade.sh, pytorch_blade/requirements-dev-1.10.0+aarch64.txt, pytorch_blade/tests/mlir/test_disc_reduction.py, pytorch_blade/tests/tensorrt/test_onnx.py, pytorch_blade/tests/test_export.py, pytorch_blade/tests/test_tools.py, scripts/ci/build_and_test.sh, scripts/ci/deploy_docker.sh, scripts/ci/deploy_tf_wrapper.sh, scripts/ci/test_pytorch_blade.sh, tao/setup.py
=> [AArch64] setup CI for aarch64 platform

torch_disc/torch_disc/csrc/disc_compiler/BUILD, torch_disc/torch_disc/csrc/disc_compiler/passes/cluster.cpp, torch_disc/torch_disc/csrc/disc_compiler/passes/disc_class.cpp, torch_disc/torch_disc/csrc/disc_compiler/passes/disc_class.h, torch_disc/torch_disc/csrc/disc_compiler/passes/register_disc_class.cpp
I have rebased `features/torch_disc_devel` to the main branch, this PR fixed some runtime errors after rebase.
=> fix rebase

.github/workflows/main.yml, pytorch_blade/src/compiler/jit/BUILD, pytorch_blade/src/compiler/jit/shape_type_spec.cpp, pytorch_blade/src/compiler/jit/shape_type_spec.h, pytorch_blade/src/compiler/jit/torch/freeze_module.cpp, pytorch_blade/src/compiler/jit/torch/freeze_module.h, pytorch_blade/src/compiler/mlir/runtime/ral_context.cpp
same as https://github.com/alibaba/BladeDISC/pull/259
=> Reopen all CI jobs on torch_disc branch 

docker/dev/Dockerfile, docker/dev/Dockerfile.torch-disc, docker/runtime/Dockerfile.pytorch, docker/scripts/find-fastest-apt.sh, docker/scripts/patch-cuda.sh, tensorflow_blade/src/tensorrt/BUILD
Now torch_blade and tf_blade has same linking behavior on static TensorRT and cuDNN.
=> [to #268] fix: tf_blade still links to shared cuDNN.

tao/tao_bridge/passes/tao_mark_for_compilation_pass.cc, tao/tao_bridge/tf/defs.cc, tao/tao_bridge/tf/defs.h, tao/tao_bridge/tf/xla_cluster_util.cc
=> To support jit scope

tao_compiler/mlir/disc/tests/regression/data/transpose_simplifier_test0.mlir, tao_compiler/mlir/disc/tests/regression/transpose_simplifier.cc, tao_compiler/mlir/disc/transforms/disc_transpose_simplifier.cc, tao_compiler/mlir/disc/transforms/tests/disc-transpose-simplifier.mlir
* add some debug logs;
* add a new pattern:
```
convert:
const ---
\
v
y -> transpose^{-1} -> add -> ... -> transpose -> yyy
\
-> ... -> zzz
to:
const' --
\
v
y -> add -> ... -> yyy
\
-> transpose^{-1} ... -> zzz
```
=> Enhance transpose simplifier pass

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_compiler.h, tao_compiler/mlir/disc/disc_compiler_main.cc, tao_compiler/mlir/disc/tests/regression/data/layer_norm.mlir, tao_compiler/mlir/disc/tests/regression/data/softmax.mlir, tao_compiler/mlir/disc/transforms/codegen_utils.cc, tao_compiler/mlir/disc/transforms/codegen_utils.h, tao_compiler/mlir/disc/transforms/disc_gpu_kernel_to_blob.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir, tao_compiler/mlir/disc/transforms/tests/specialize_fusion_with_speculation.mlir
Reads the GPU architecture information and enhances the codegen schedule selection.
=> Arch-aware schedule selection enhancement for GPU fusion.

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/tests/mlir_feature_test.cc, tao_compiler/mlir/disc/transforms/disc_dot_merge.cc, tao_compiler/mlir/disc/transforms/disc_specialize_fusion_with_speculation.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.cc, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.h, tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.h, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/parallel_loop_collapsing.cc, tao_compiler/mlir/disc/transforms/parallel_loop_tiling.cc, tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir
1. Interleave the codegen schedule of independent row-reduce ops in the same kStitch fusion.
2. Some other detailed codegen schedule optimizations.
=> Row-reduce ops interleave for kStitch codegen.

pytorch_blade/src/ltc/disc_compiler/disc_compiler.cpp, pytorch_blade/src/ltc/disc_compiler/passes/register_disc_class.cpp
enable logs with
``` bash
PYTORCH_JIT_LOG_LEVEL=">>registry_disc_class:disc_compiler" python mnist.py
```
=> logging disc compilation logs in torchDisc

pytorch_blade/src/ltc/disc_compiler/BUILD
=> remove torch_blade.so dep from torch_disc.so

pytorch_blade/.bazelrc, pytorch_blade/bazel_build.py, pytorch_blade/ci_build/build_pytorch_blade.sh, tao_compiler/mlir/disc/transforms/codegen_utils.cc, tao_compiler/mlir/disc/transforms/shape_utils.cc
1. categorize the configurations and settings
2. build disc_compiler_main with opt compilation mode
3. fix DEBUG mode compilation
=> [Torch] Add debug mode cpp test

.github/workflows/main.yml
=> Fix deploy CI job

tao/tao_bridge/passes/tao_mark_for_compilation_pass.cc, tao_compiler/mlir/disc/transforms/conv_rewriter.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
* support ACL conv directly
* support ACL depthwise_cnov directly
* support pre-packing for ACL conv/depthwise_conv/qconv
=> support acl conv + depthwise_conv

docker/dev/Dockerfile.torch-disc, pytorch_blade/.bazelrc, pytorch_blade/BUILD.bazel, pytorch_blade/bazel/build_defs.bzl, pytorch_blade/bazel_build.py, pytorch_blade/ci_build/build_pytorch_blade.sh, pytorch_blade/distribution.cfg, pytorch_blade/setup.py, pytorch_blade/src/BUILD, pytorch_blade/src/compiler/mlir/BUILD, pytorch_blade/src/compiler/mlir/converters/mhlo_converter_register.cpp, pytorch_blade/src/ltc/BUILD, pytorch_blade/src/ltc/disc_backend/backend_impl.cpp, pytorch_blade/src/ltc/disc_compiler/BUILD, pytorch_blade/src/ltc/init_python_bindings.cpp, pytorch_blade/src/pybind.cpp, pytorch_blade/tests/ltc/__init__.py, pytorch_blade/tests/ltc/test_mnist.py, pytorch_blade/torch_blade/__init__.py, scripts/ci/test_torch_disc.sh
=> [code refactor]merge torch_blade and torch_disc library

pytorch_blade/src/torch-mlir/BUILD, pytorch_blade/src/torch-mlir/include/torch-mlir/Conversion/MhloPasses.h, pytorch_blade/src/torch-mlir/lib/Conversion/MhloPasses.cpp, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/tests/mhlo/elementwise.mlir, pytorch_blade/tests/mhlo/ops.mlir, pytorch_blade/tests/mhlo/torch-mlir-opt/torch-mlir-opt.cpp
=> enable filecheck ut for torch-to-mhlo-pass

pytorch_blade/ci_build/build_pytorch_blade.sh, pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.cpp, pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.h, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.h, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/tests/disc/ops/test_activation.py, pytorch_blade/tests/disc/ops/test_binary_ops.py, pytorch_blade/tests/disc/ops/test_unary_ops.py
=> [TorchMLIR]add TorchMLIR converter op filter

scripts/python/tao_build.py, tao_compiler/mlir/disc/transforms/shape_utils.cc, tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-legalize-roots-to-loops.mlir, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
- Fix shape utils error in disc compiler
- Disable ROCm disc-replay compilation for later support
=> Fix tao compiler error

pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp
@wyzero I had sorted the white list.
=> Resort the TorchMLIR white list

pytorch_blade/scripts/build_pytorch_blade.sh, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/src/torch-mlir/lib/Dialect/TorchConversion/Transforms/ApplyValueSemantics.cpp, pytorch_blade/src/torch-mlir/lib/Dialect/TorchConversion/Transforms/ReduceTensorConversions.cpp, pytorch_blade/src/torch-mlir/lib/Dialect/TorchConversion/Transforms/VerifyMhloBackendContract.cpp, pytorch_blade/tests/disc/ops/test_shapes.py, pytorch_blade/tests/disc/ops/test_slices.py, pytorch_blade/tests/mhlo/views.mlir
- Sort the TorchMLIR white list
- Add shapes and views
=> Add shapes and views

pytorch_blade/scripts/build_pytorch_blade.sh, pytorch_blade/src/compiler/mlir/converters/impl/shapes.cpp, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/src/torch-mlir/include/torch-mlir/Conversion/TorchToMhlo/MhloLegalizeUtils.h, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/src/torch-mlir/lib/Dialect/TorchConversion/Transforms/ApplyValueSemantics.cpp, pytorch_blade/tests/disc/ops/test_mem_ops.py, pytorch_blade/tests/disc/ops/test_slices.py, pytorch_blade/tests/disc/testing_base.py, pytorch_blade/tests/mhlo/slices.mlir
- Sort the TorchMLIR white list
- [TorchMhlo] add slices
=> [TorchMhlo] add slices

.github/workflows/cronjobs.yml, .github/workflows/reusable.yml
=> [CI] fix and tune cronjobs

pytorch_blade/src/compiler/mlir/converters/mhlo_conversion.cpp, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp
Add the following debug messages and utils:
1. Add mhlo white list warning messages and custom white list configure env variable
2. Add llvm diagnosis messages
3. Add GRAPH_DUMP message before TorchToMhlo conversion
=> [TorchMhlo] Add debug messages

pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/tests/disc/ops/test_matmul.py, pytorch_blade/tests/mhlo/matmul_half.mlir
Torch-MLIR hasn't supported fp16 conversion before. The pull request adds the fp16 support.
=> [TorchMhlo] Add fp16 support

.github/workflows/cronjobs.yml, .github/workflows/reusable.yml, docker/cronjobs/Dockerfile.torch.bench, pytorch_blade/benchmark/TorchBench/test_torch_bench.sh
Integrate torchbench in cronjob
=> [CI] Torchbench cronjob

pytorch_blade/scripts/build_pytorch_blade.sh, pytorch_blade/src/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/TorchToMhlo.cpp, pytorch_blade/tests/disc/ops/test_layer_norm.py, pytorch_blade/tests/disc/ops/test_nn_ops.py, pytorch_blade/tests/mhlo/layer_norm.mlir, pytorch_blade/tests/mhlo/ops.mlir
Please also review https://github.com/pai-disc/torch-mlir/pull/13
1. Add layernorm decomposition in https://github.com/pai-disc/torch-mlir/pull/13
2. Add layernorm e2e ut and filecheck
=> [TorchMhlo] Add layernorm

pytorch_blade/src/compiler/jit/torch/op_registry.cpp, pytorch_blade/src/compiler/jit/torch/shape_analysis.cpp
add softmax_backward, nll_loss_backward, native_layer_norm_backward in shape analysis pass
related #473
=> add some backward ops shape analysis

.github/workflows/pytorch171_gpu.yml, .github/workflows/pytorch181_gpu.yml, pytorch_blade/scripts/pip/requirements-dev-1.8.1+cu102.txt, pytorch_blade/scripts/pip/requirements-dev-1.8.1+cu111.txt
The PR resolve the following issue:
1. Add torch 1.8.1+cu111 CI
2. Fix CI failure of deploy stage
=> Fix PyTorch CI

scripts/python/common_setup.py, tao_compiler/mlir/xla/ral/context/common_context_impl.h, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, third_party/bazel/acl/acl_makefile.patch
* using single thread scheduler when OMP_NUM_THREADS=1
* using OMP scheduler if `DISC_ACL_SCHEDULER_TYPE=OMP`
=> [AArch64] make ACL thread scheduler configurable

pytorch_blade/tests/quantization/__init__.py, pytorch_blade/tests/quantization/test_data_prepare.py, pytorch_blade/tests/quantization/test_graph_process.py, pytorch_blade/torch_blade/clustering/support_group_conversion.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/quantization/prepare_data.py, pytorch_blade/torch_blade/tools/shape_inference.py
This pr contains two parts mentioned #514 
+ make each subgraph executable
+ save data for each fusion group
=> [Quantization] Add data collector for trt ptq

pytorch_blade/tests/disc/test_disc_engine.py, pytorch_blade/tests/tensorrt/test_tensorrt.py, pytorch_blade/torch_blade/mlir/__init__.py, pytorch_blade/torch_blade/tensorrt/__init__.py, pytorch_blade/torch_blade/utils.py
=> add counter for blade compiled nodes.

examples/TensorFlow/Inference/AArch64/BERT/download_model.sh, examples/TensorFlow/Inference/CUDA/BERT/download_model.sh, examples/TensorFlow/Inference/CUDA/FastSpeech2/download_model.sh, examples/TensorFlow/Inference/X86/BERT/download_model.sh, scripts/python/common_setup.py, tensorflow_blade/workspace0.bzl, third_party/bazel/blade_disc_dnn_workspace.bzl
Trying to resolve terrible network from zhangjiakou to hongkong.
=> accelerate downloading from HK

mhlo_builder/csrc/mlir/mhlo/builder/matmul.cpp, pytorch_blade/src/torch-mlir/BUILD, pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/MhloLegalizeUtils.cpp, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/runlit.site.cfg.py, tao_compiler/mlir/disc/tests/tensorflow_ops/data/batch_matmul_nn_p_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/batch_matmul_nt_p_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/batch_matmul_tn_p_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/batch_matmul_tt_p_f32.mlir, tao_compiler/mlir/disc/tools/disc-replay/BUILD, tao_compiler/mlir/disc/transforms/lower_tf.cc, tao_compiler/mlir/disc/transforms/lower_tf.td
1. Mainly update `mlir-hlo` directory from `tensorflow/compiler/mlir/hlo` to `tensorflow/compiler/xla/mlir_hlo`
2. Fix mhlo::DotGeneral contracting dimension sizes for lhs/rhs
3. Update e2e check for batch matmul
=> Rebase tensorflow aicompiler_rebase_20220804

pytorch_blade/scripts/pip/requirements-dev-1.12.0+cu113.txt
sometimes it would install rocm torchvision
=> fix torchvision version error in cu113

.github/workflows/pytorch190_gpu.yml
install 1.9.1+cu111 incorrectly...
=> Fix torch 1.9.0 deploy docker

.github/workflows/cronjobs.yml, .github/workflows/reusable.yml
docker build do not have "--cap-add" args
=> fix cronjob build docker error

scripts/python/tao_build.py, tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/IR/tests/BUILD, tao_compiler/mlir/disc/IR/tests/invalid_hlo_disc.mlir, tao_compiler/mlir/disc/IR/tests/ops_hlo_disc.mlir
=> [quantization] add fake_quant/quantize/dequantize op def

docker/runtime/Dockerfile.pytorch
failed deploy like https://github.com/alibaba/BladeDISC/actions/runs/2908257349
=> [CI] fix deploy dockerfile

tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.h, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/IR/tests/invalid_hlo_disc.mlir, tao_compiler/mlir/disc/IR/tests/ops_hlo_disc.mlir
=> [quantization] add quantized_gemm/quantized_conv op def

tao_compiler/mlir/disc/transforms/fusion_utils.cc
Some ternary ops (e.g. select op) support a restricted implicit broadcast
semantic, that is: if one input has rank zero, then it will be
automatically broadcasted if necessary. Thus we can know that
there is no broadcast if all operands have the same rank, which means
it's also a pure element wise op.
=> [fusion] add ternary element wise op list

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/transforms/PassDetail.h, tao_compiler/mlir/disc/transforms/disc_lower_quantize_and_dequantize.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/disc-lower-quantize-and-dequantize.mlir
=> [quantization] lower mhlo_disc.quantize op

tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/transforms/disc_hlo_legalize_to_lhlo.cc, tao_compiler/mlir/disc/transforms/disc_map_hlo_to_lhlo_op.h, tao_compiler/mlir/disc/transforms/tests/disc-hlo-legalize-to-lhlo.mlir
=> [quantization] bufferize mhlo_disc::QuantizedDynamicConvOp

pytorch_blade/src/torch-mlir/lib/Conversion/TorchToMhlo/DiscTorchToMhlo.cpp, pytorch_blade/tests/mhlo/reduction.mlir, pytorch_blade/tests/mhlo/softmax.mlir
- enable merkle tree cache in torch_blade
- Pick AtenMaxDimOp Reduction that had been revert
=> Pick AtenMaxDimOp Reduction that had been revert

.github/workflows/auto_rebase.yml, .github/workflows/d2_trt_bench.yml, .github/workflows/reusable.yml, .github/workflows/torchbench.yml, pytorch_blade/benchmark/TorchBench/test_torch_bench.sh, scripts/ci/ossutil
1. upload summary after TorchBench
2. split cronjobs
3. delete auto rebase from cronjobs
=> Refine && test ci workflow

tao_compiler/mlir/disc/IR/lhlo_disc_ops.cc, tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/IR/rng_uniform_custom_call_op.cc, tao_compiler/mlir/disc/IR/sparse_custom_call_op.cc, tao_compiler/mlir/disc/IR/topk_custom_call_op.cc, tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc, tao_compiler/mlir/disc/transforms/disc_to_llvm.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/placement_utils.cc, tao_compiler/mlir/disc/transforms/tests/disc-lower-to-library-call.mlir
=> [quantization] lower lmhlo_disc::quantized_dynamic_conv to library call

pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_onnx_parser.cpp, pytorch_blade/src/compiler/tensorrt/bridge/tensorrt_onnx_parser.h, pytorch_blade/src/compiler/tensorrt/pybind_functions.cpp, pytorch_blade/tests/quantization/test_data_prepare.py, pytorch_blade/tests/tensorrt/test_trt_extension.py, pytorch_blade/torch_blade/clustering/support_fusion_group.py, pytorch_blade/torch_blade/clustering/support_group_conversion.py, pytorch_blade/torch_blade/mlir/disc_engine_conversion.py, pytorch_blade/torch_blade/onnx_backends/backend_conversion.py, pytorch_blade/torch_blade/onnx_backends/backend_testbed.py, pytorch_blade/torch_blade/optimization.py, pytorch_blade/torch_blade/tensorrt/dynamic_shapes.py, pytorch_blade/torch_blade/tensorrt/tensorrt_optimization.py
Also apply linter to the codes
=> [Quantization] remove all q_val & q_info

tao_compiler/mlir/disc/transforms/disc_lower_quantize_and_dequantize.cc, tao_compiler/mlir/disc/transforms/tests/disc-lower-quantize-and-dequantize.mlir
=> [quantization] lower mhlo_disc::DequantizeOp

tao_compiler/mlir/disc/transforms/disc_convert_fake_quant_op.cc, tao_compiler/mlir/disc/transforms/tests/disc-convert-fake-quant-op.mlir
=> [quantization] mhlo_disc::fake_quant + mhlo::convolution -> qconv

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tests/tensorflow_ops/data/quantized_conv2d_p_nhwc_i8_per_channel.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/quantized_conv2d_s_nhwc_i8_per_channel.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/quantized_conv2d.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
=> [quantization][AArch64] add s8s8s8 per-channel quantized_conv uts

tao_compiler/mlir/disc/IR/hlo_disc_ops.cc, tao_compiler/mlir/disc/IR/hlo_disc_ops.td, tao_compiler/mlir/disc/transforms/disc_hlo_legalize_to_lhlo.cc, tao_compiler/mlir/disc/transforms/disc_map_hlo_to_lhlo_op.h, tao_compiler/mlir/disc/transforms/tests/disc-hlo-legalize-to-lhlo.mlir
=> [quantization] bufferize mhlo_disc::QuantizedDotGeneralOp

tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc, tao_compiler/mlir/disc/transforms/tests/disc-lower-to-library-call.mlir
=> [quantization] lower quantized_dot_general to library call

tao_compiler/mlir/disc/transforms/disc_convert_fake_quant_op.cc, tao_compiler/mlir/disc/transforms/tests/disc-convert-fake-quant-op.mlir
=> [quantization] mhlo_disc::fake_quant + gemm + fake_quant -> qgemm

tao_compiler/mlir/disc/tests/tensorflow_ops/data/quantized_matmul_p_i8_per_channel.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/data/quantized_matmul_s_i8_per_channel.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/quantized_matmul.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_acl.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_acl.h, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
=> [quantization] add UTs for s8s8s8 per-channel qgemm on AArch64

pytorch_blade/src/compiler/jit/torch/shape_analysis.cpp, tao_compiler/mlir/disc/transforms/disc_transpose_simplifier.cc
1. Fix shape analysis for aten::linear
2. Fix transpose simplifier
=> Fix alexnet optimization

scripts/ci/test_pytorch_blade.sh
=> fix GC disk cache bug

tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp
=> [quantization] add x86 quantization gemm kernel with s8s8s8 format

tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h
Depthwise conv op has been refactored to support parallel `op.run...()`. This CL changes accordingly to enable such feature.
=> [AArch64] re-use ACL depthwise operator instance for different threads

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/tests/tensorflow_ops/data/quantized_matmul_p_i8_per_tensor.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/quantized_matmul.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/mhlo_placer.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/quantized_dot_rewriter.cc, tao_compiler/mlir/disc/transforms/tests/quantized-disc-dot-rewriter.mlir, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
=> [quantization] Support qgemm int8 for BladeDISC on GPU

pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp
The PR should fix the bug found in issue #692.
=> fix aten::slice shape propogation

pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscDecomposeComplexOps.cpp, pytorch_blade/tests/disc/ops/test_unary_ops.py
Those conversions fixups are needed to run ResNet50(amp) and hfAlbert
=> Fix some conversions

pytorch_blade/bazel_build.py, pytorch_blade/pytorch_blade/common_utils/macros.h, pytorch_blade/pytorch_blade/compiler/jit/torch/op_registry.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis_test.cpp
This PR add some op shape analysis, to make this pass more stable, better to add a unit test to check the static shape and dynamic shape for a new op.
=> enhancement shape analysis pass 

.github/workflows/pytorch_pre_gpu.yml, docker/runtime/Dockerfile.pytorch, docker/scripts/find-fastest-apt.sh, pytorch_blade/bazel_build.py, pytorch_blade/pytorch_blade/compiler/jit/shape_type_spec.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/compiler/mlir/runtime/ral_context.cpp, pytorch_blade/pytorch_blade/compiler/tensorrt/bridge/tensorrt_onnx_parser.cpp, pytorch_blade/pytorch_blade/compiler/tensorrt/tensorrt_engine_context.cpp, pytorch_blade/pytorch_blade/ltc/include/torch/csrc/lazy/ts_backend/ops/to_copy.h, pytorch_blade/scripts/pip/requirements-dev-pre+cu117.txt, pytorch_blade/tests/disc/ops/test_binary_ops.py, pytorch_blade/tests/disc/ops/test_list.py, pytorch_blade/tests/disc/testing_base.py, pytorch_blade/tests/ltc/test_mnist.py, pytorch_blade/tests/test_tools.py, pytorch_blade/torch_blade/clustering/support_fusion_algorithm.py, pytorch_blade/torch_blade/config.py, pytorch_blade/torch_blade/utils.py
This PR adds a nightly preview torch version into CI. It fixes and updates the following things:
1. fix apt sources establishment in Dockerfile
2. fix compilation errors introduced by API changes of Torch
=> Add pre-built torch into ci

scripts/python/common_setup.py
Try a stable choice of downloading and extracting tar.
=> Change download script for mkl

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_dot_gpu.cc, tao_compiler/mlir/disc/transforms/input_inline_fusion_pass.cc, tao_compiler/mlir/disc/transforms/input_inline_fusion_pattern.h, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-fusion.mlir
This PR depends on https://github.com/alibaba/BladeDISC/pull/718. It will be rebased after https://github.com/alibaba/BladeDISC/pull/718 is merged.
=> Basic fusion decision functions of dot operators.

pytorch_blade/tests/torch-disc-pdll/tests/fake_quant.mlir, pytorch_blade/tests/torch-disc-pdll/tests/fake_quant.pdll, pytorch_blade/tests/torch-disc-pdll/utils.cpp
torch.operator "fake_quant" -> torch.operator "quantize" + torch.operator "dequantize"
=> [PDLL] Fake quant convert

pytorch_blade/tests/torch-disc-pdll/tests/dequant_qgemm_quant.mlir, pytorch_blade/tests/torch-disc-pdll/tests/dequant_qgemm_quant.pdll
dequant+gemm+quant -> qgemm
Parsed Payload module:
Rewrited Payload module:
=> [PDLL] Add torch qgemm pattern match

tao_compiler/mlir/disc/tests/regression/data/where_fusion_d_3d_i64.mlir, tao_compiler/mlir/disc/tests/regression/where_fusion.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/mhlo_mark_shape_calc.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-where.mlir
#742 
With bug fix for `DiscMarkShapeCalc` pass when running regression test for a `embedding column` subgraph.
=> impl of where fusion

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-lmhlo-fusion.mlir
It's the first step to support transform dialect in BladeDISC.
=> [transform] add transform-based fusion strategy.

.gitmodules, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/disc_util.h, tao_compiler/mlir/disc/tests/regression/data/epilogue_fusion_gemm_gelu_f16.mlir, tao_compiler/mlir/disc/tests/regression/data/epilogue_fusion_gemm_gelu_f32.mlir, tao_compiler/mlir/disc/tests/regression/epilogue_fusion.cc, tao_compiler/mlir/disc/transforms/disc_comp_intens_fusion_to_cuda_source.cc, tao_compiler/mlir/disc/transforms/disc_comp_intens_fusion_to_func.cc, tao_compiler/mlir/disc/transforms/disc_convert_const_to_ral.cc, tao_compiler/mlir/disc/transforms/disc_gpu_source_to_lib.cc, tao_compiler/mlir/disc/transforms/disc_lower_to_library_call.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/disc_to_llvm.cc, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/utils/cutlass_required_headers.cu, tao_compiler/mlir/disc/utils/gemm_fusion_linear_base_template.hpp, tao_compiler/mlir/disc/utils/gemm_fusion_linear_base_template_sm75.hpp, tao_compiler/mlir/disc/utils/gemm_fusion_linear_base_template_sm80.hpp, tao_compiler/mlir/disc/utils/preprocess_cutlass_headers.sh, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
Depends on https://github.com/alibaba/BladeDISC/pull/718 and https://github.com/alibaba/BladeDISC/pull/719. Will be rebased after the dependencies are merged.
=> Code generation of compute-intensive centric fusion.

tao_compiler/mlir/disc/IR/lhlo_disc_ops.td, tao_compiler/mlir/disc/transforms/lhlo_legalize_roots_to_loops.cc
=> Support to print parameter size of fusion through setting environment.

docker/dev/Dockerfile, docker/dev/Dockerfile.aarch64, scripts/python/tao_build.py, tao/BUILD, third_party/bazel/tf/build_defs.bzl.tpl, third_party/bazel/tf/tf_configure.bzl
Support sdk packing for tensorflow side, which can be used for tensorflow-serving build with `DISC`. 
Tested in internal `unibuild` pipeline.
=> package for tf serving

examples/PyTorch/Inference/CPU/albert/requirements.txt, examples/PyTorch/Inference/CPU/albert/test.sh, examples/PyTorch/Inference/CUDA/BERT/requirements.txt, examples/PyTorch/Inference/CUDA/BERT/test.sh, examples/PyTorch/Inference/CUDA/ResNet/test.sh, examples/PyTorch/Inference/CUDA/S2T/requirements.txt, examples/PyTorch/Inference/CUDA/S2T/test.sh, examples/PyTorch/Inference/CUDA/T5/main.py, examples/PyTorch/Inference/CUDA/T5/requirements.txt, examples/PyTorch/Inference/CUDA/T5/test.sh, pytorch_blade/scripts/build_pytorch_blade.sh
mark related to https://github.com/alibaba/BladeDISC/issues/785
=> Init PyTorch examples ci scripts

examples/PyTorch/Inference/CUDA/BERT/requirements.txt, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/torch-mlir/BUILD, pytorch_blade/pytorch_blade/torch-mlir/include/torch-mlir/Conversion/MhloPasses.h, pytorch_blade/pytorch_blade/torch-mlir/include/torch-mlir/Conversion/MhloPasses.td, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/MhloPasses.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/UpgradeLegacyOps.cpp, pytorch_blade/tests/disc/ops/test_activation.py
This PR provides a method to detect op compatibility verification and upgrading.
Mark related to https://github.com/alibaba/BladeDISC/issues/785, https://github.com/alibaba/BladeDISC/issues/408
=> Add legacy operator upgrade pass

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/disc-bufferize.mlir
=> [transform] bufferize tensor.empty

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/disc-bufferize.mlir
=> [transform] promote some buffers to stack if possible

pytorch_blade/bazel_build.py, pytorch_blade/torch_blade_build.py, scripts/python/common_setup.py, scripts/python/tao_build.py, tao_compiler/.bazelrc.user, tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/disc.bzl, tao_compiler/mlir/disc/transforms/disc_gpu_source_to_lib.cc
blade gemm is not needed for `compiler` side build, thus remove related build logic.
=> refinement for internal build about `blade gemm` and `compute intensive fusion`

pytorch_blade/scripts/pip/requirements-dev-1.10.0+aarch64.txt, pytorch_blade/scripts/pip/requirements-dev-1.12.0+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-1.12.0+cu113.txt, pytorch_blade/scripts/pip/requirements-dev-1.6.0+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-1.7.1+cu110.txt, pytorch_blade/scripts/pip/requirements-dev-1.8.1+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-1.8.1+cu111.txt, pytorch_blade/scripts/pip/requirements-dev-1.9.0+cu111.txt, pytorch_blade/scripts/pip/requirements-dev-pre+cu117.txt, pytorch_blade/tests/disc/pdl/pdll_files/cpu/dequant_gemm_quant.pdll, pytorch_blade/tests/disc/pdl/test_e2e/__init__.py, pytorch_blade/tests/disc/pdl/test_e2e/test_quantization.py, pytorch_blade/tests/disc/pdl/test_torchscipt_to_mhlo/test_quantization.py, pytorch_blade/tests/disc/testing_base.py, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp
1. a pdl qgemm kernel with bias support (rank=2 for operand 1)
2. a e2e test case for x86 platform with acc check
=> [Quantization][PDL] pdll qgemm kernel for x86 and a e2e test

tao_compiler/mlir/disc/tests/disc-transform/data/matmul_nn_d_f32_large_schedule_2.mlir, tao_compiler/mlir/disc/tests/disc-transform/matmul.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/apply-patterns-canonicalization.mlir
=> [transform] fuse linalg.fill into gemm

pytorch_blade/tests/disc/pdl/pdll_files/gpu/dequant_gemm_quant_bias_quant.pdll, pytorch_blade/tests/disc/pdl/test_torchscipt_to_mhlo/test_quantization.py, pytorch_blade/tests/torch-disc-pdll/utils.cpp
The target of this pr is to be compatible with int8 kernel implementation, namely int32 biasadd for cpu and int8 biasadd for gpu.
=> [Quantization] Add bias quant

tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.h, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.td, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/cache-read.mlir
=> [transform] add a disc.cache_read transform primitive

tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtBase.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtDialect.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/tests/canonicalize.mlir
=> [transform] add fold support for disc_linalg_ext::MultiLevelPackOp

pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/MhloPasses.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/TorchToMhlo/DiscTorchToMhlo.cpp
Add some new converters increasing the op coverage of Bert's training https://github.com/alibaba/BladeDISC/issues/766
=> Add some new torch2mhlo converters

tao_compiler/mlir/disc/transforms/disc_std_bufferize.cc
=> bufferize arith.constant with rank 0

scripts/python/common_setup.py
=> Revert "fix internal build"

tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-lmhlo-fusion.mlir
=> [transform] support fuse const weight into kTransform fusion pattern

pytorch_blade/tests/disc/pdl/pdll_files/common/fake_quant.pdll, pytorch_blade/tests/disc/pdl/pdll_files/cpu/dequant_gemm_quant.pdll, pytorch_blade/tests/disc/pdl/test_e2e/test_quantization.py, pytorch_blade/tests/disc/pdl/test_torchscipt_to_mhlo/test_quantization.py, pytorch_blade/tests/disc/testing_base.py, pytorch_blade/tests/torch-disc-pdll/tests/fake_quant.pdll, pytorch_blade/tests/torch-disc-pdll/utils.cpp, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.cc, tao_compiler/mlir/xla/ral/context/common_context_impl_mkldnn.h, tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc
1. acl qgemm with bias 
2. pre-packing for bias
3. seperate output stage with qgemm to avoid numerical overflow
=> [Quantization]QGemm with bias kernel for aarch64

tao_compiler/mlir/disc/tests/regression/data/epilogue_fusion_transpose_bmm0213.mlir, tao_compiler/mlir/disc/tests/regression/epilogue_fusion.cc, tao_compiler/mlir/disc/transforms/disc_algebraic_simplifier.cc, tao_compiler/mlir/disc/transforms/disc_comp_intens_fusion_to_cuda_source.cc, tao_compiler/mlir/disc/transforms/fusion_utils_dot_gpu.cc, tao_compiler/mlir/disc/utils/gemm_fusion_linear_base_template_sm75.hpp, tao_compiler/mlir/disc/utils/gemm_fusion_linear_base_template_sm80.hpp, tao_compiler/mlir/disc/utils/source_emitter.cc, tao_compiler/mlir/disc/utils/source_emitter.h
It supports single transpose in the epilogue of `kDot` fusion.
=> Support transpose fusion of kDot.

pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/ApplyDiscPdlPatterns.cpp, pytorch_blade/tests/disc/ops/test_group_norm.py, pytorch_blade/tests/torch-disc-pdll/utils.cpp, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc
related to #867 , add group_norm codegen
related submodule pr https://github.com/pai-disc/torch-mlir/pull/25
=> support group norm lowering

tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_stitch_gpu.cc, tao_compiler/mlir/xla/ral/BUILD, tao_compiler/mlir/xla/ral/context/custom_library/transpose_gpu.cu.cc, tao_compiler/mlir/xla/ral/context/transpose_impl.cc
=> supports fp16 2d/3d transpose

tao_compiler/decoupling/mlir_compiler.cc, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_d_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_p_2x768_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_p_512x1024_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_p_768x2_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_s_24x24x64_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nn_s_24x64x24_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/default_schedule_matmul.cc, tao_compiler/mlir/disc/tests/disc-transform/packed_matmul.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/transform_dialect_interpreter.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.h
=> [transform] make the default schedule support small shape

.github/workflows/pytorch113_aarch64.yml, pytorch_blade/scripts/pip/requirements-dev-1.13.1+aarch64.txt, pytorch_blade/tests/disc/ops/test_binary_ops.py, pytorch_blade/tests/test_tools.py, pytorch_blade/torch_blade/config.py
torch-nightly does not fit for aarch64, use 1.13.1 instead
=> add Torch 1.13.1 aarch64 CI

pytorch_blade/torch_blade_build.py
Fix internal uni-build bugs that bazel configuration about neural engine is missing.
=> disable neural engine by default

.github/workflows/torchbench.yml, pytorch_blade/benchmark/TorchBench/requirements_aarch64.txt, pytorch_blade/benchmark/TorchBench/requirements_cpu.txt, pytorch_blade/benchmark/TorchBench/requirements_cuda.txt, pytorch_blade/benchmark/TorchBench/test_torch_bench.sh
triggered at https://github.com/alibaba/BladeDISC/actions/runs/3799369409
=> [TorchBench] upgrade benchmark

tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_nt_d_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_tn_d_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/default_schedule_matmul_tt_d_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/default_schedule_matmul.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/legalize_lmhlo_fusion_to_linalg.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/legalize-lmhlo-fusion-to-linalg.mlir, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc
=> [transform] support nt/tn/tt mamtul

tao_compiler/mlir/disc/tests/disc-transform/default_schedule_matmul.cc, tao_compiler/mlir/disc/tests/disc-transform/matmul.cc, tao_compiler/mlir/disc/tests/disc-transform/matmul_multithread.cc, tao_compiler/mlir/disc/tests/disc-transform/packed_matmul.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/lower-multi-level-pack-to-loop.mlir
=> [transform] inject some static info whenever possible

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/inline-reduction-initializer.mlir
=> [transform] inline reduction initializer

pytorch_blade/benchmark/TorchBench/requirements_cpu.txt, pytorch_blade/benchmark/TorchBench/requirements_cuda.txt, pytorch_blade/benchmark/TorchBench/test_torch_bench.sh, pytorch_blade/scripts/pip/requirements-dev-pre+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-pre+cu117.txt
triggered at https://github.com/alibaba/BladeDISC/actions/runs/3853713949
=> Update benchmark version

tao_compiler/mlir/disc/tests/disc-transform/data/use_inlined_code_input_code.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/use_inlined_code_input_computation.mlir, tao_compiler/mlir/disc/tests/disc-transform/use_inlined_code.cc, tao_compiler/mlir/disc/transforms/disc_transform_legalize_to_loop.cc
=> [transform][debug] hijack codegen pipeline and use provided code directly

pytorch_blade/torch_blade/dynamo/__init__.py, pytorch_blade/torch_blade/pass_manager.py, pytorch_blade/torch_blade/python_ir_analysis.py
=> disable const propagating on training with Dynamo

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/decompose-vectors.mlir, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc
=> [transform] add primitive to decompose vector ops to smaller ones

pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/TorchToMhlo/DiscTorchToMhlo.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscDecomposeComplexOps.cpp, pytorch_blade/tests/disc/ops/test_nn_ops.py, pytorch_blade/tests/torchscript/basics.graph, tao_compiler/mlir/disc/transforms/mhlo_decomp_rewriters.cc
The PR is needed to compile paraformer:
1. add support to aten::pad
2. inference `aten.split.Tensor` output's chunk number for the static shape of the input
=> [PT2.0] Support paraformer

tao_compiler/mlir/xla/ral/context/common_context_impl_quantization.cc, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/abstract_types.hpp, tao_compiler/mlir/xla/ral/context/mkldnn/ideep/ideep/operators/matmul.hpp
So we can get the primitive states of one-dnn and further make it more easier for enabling weight pre-packing
=> separate preparing & computing process of calling onednn kernel

tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/transforms/legalize_lmhlo_fusion_to_linalg.cc, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/legalize-lmhlo-fusion-to-linalg.mlir
=> [transform] legalize bcast/elem lmhlo ops to linalg

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/linalg-fuse-operand.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/linalg-fuse-producers.mlir
=> [transform] add transform primitives to fuse linalg elem ops

tao_compiler/mlir/disc/tests/disc-transform/data/matmul_epilogue_biasadd_p_768x3072_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/matmul_epilogue_biasadd_relu_p_768_3072_f32.mlir, tao_compiler/mlir/disc/tests/disc-transform/data/matmul_epilogue_complex_test0.mlir, tao_compiler/mlir/disc/tests/disc-transform/matmul_epilogue.cc, tao_compiler/mlir/disc/tools/disc-transform/BUILD, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.cc, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.h, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/LinalgExtOps.td, tao_compiler/mlir/disc/tools/disc-transform/LinalgExt/tests/ops.mlir, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/convert-padding-placeholder-to-const.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/replace-const-padding-value.mlir, tao_compiler/mlir/disc/transforms/disc_transform_legalize_to_loop.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.cc, tao_compiler/mlir/disc/transforms/disc_transform_schedule.h, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc
=> [transform] epilogue fusion for gemm schedule w/o split k

.github/workflows/pytorch113_gpu.yml, pytorch_blade/scripts/pip/requirements-dev-1.13.1+cu116.txt
=> [Testing] Add PyTorch 1.13.1 + CUDA 11.6 CI

pytorch_blade/pytorch_blade/compiler/jit/torch/op_registry.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/compiler/mlir/converters/torch_mlir_op_filter.cpp, pytorch_blade/tests/torch-disc-pdll/utils.cpp
co-authored with @linbinskn @minminsun
=> [Torch] add some PDL rewrite functions and op support for stable diffusion

tao_compiler/mlir/disc/BUILD, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_sparse_op_cpu.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/tests/cpu-only-sparse-op-fusion.mlir
1. Separate where fusion logic from `fusion_utils.cc`
2. set up `SparseFusionStrategy` for where fusion and upcoming `kSparseReduction` fusion
=> refactor fusion util for sparse ops

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/linalg-eagerly-backward-init-tensor.mlir
=> [transform] add a primitive to reuse output buffer

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/fuse-into-containing-op.mlir
=> [transform] fuse_into_containing supports fusion through args for scf.for

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/reduction-output-fuse.mlir
=> [transform] add reduction_output_fuse primitive

tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.cc, tao_compiler/mlir/disc/tools/disc-transform/TransformOps/TransformOpsExt.td, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/apply-patterns-canonicalization.mlir, tao_compiler/mlir/disc/tools/disc-transform/transforms/tests/vectorize-conditional-generic.mlir
=> [transform] vectorize conditional_generic op

pytorch_blade/pytorch_blade/torch-mlir/BUILD, pytorch_blade/pytorch_blade/torch-mlir/include/torch-mlir/Conversion/MhloPasses.h, pytorch_blade/pytorch_blade/torch-mlir/include/torch-mlir/Conversion/MhloPasses.td, pytorch_blade/pytorch_blade/torch-mlir/lib/Conversion/MhloPasses.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscDecomposeComplexOps.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscSimplifyPatterns.cpp, pytorch_blade/tests/mhlo/disc_simlifier.mlir, pytorch_blade/tests/mhlo/split.mlir
=> lowering dynamic shape split op in torch-blade

pytorch_blade/WORKSPACE, tao_compiler/WORKSPACE, tao_compiler/build_tools/bazel/workspace.bzl, tao_compiler/third_party/iree/StructuredTransformOpsExt.cpp.patch
related changes: https://github.com/pai-disc/tensorflow/pull/29
=> import iree in compiler workspace instead of tf workspace

pytorch_blade/pytorch_blade/compiler/jit/BUILD, pytorch_blade/pytorch_blade/compiler/jit/torch/BUILD, pytorch_blade/pytorch_blade/compiler/jit/torch/constant_propagation.cpp, pytorch_blade/pytorch_blade/compiler/jit/torch/constant_propagation.h, pytorch_blade/pytorch_blade/pybind.cpp, pytorch_blade/tests/disc/test_const_propagation.py, pytorch_blade/torch_blade/exporter.py
This PR added a simple const propagation pass to work around const tensor dealing failed on the DISC pipeline.
=> Add simple const propagation for training 

tao_compiler/mlir/disc/tests/tensorflow_ops/data/inline_h2d_d_f32.mlir, tao_compiler/mlir/disc/tests/tensorflow_ops/inline_h2d.cc, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/lhlo_elemental_utils.cc
enhance scalar h2d fusion feature to support all fusion types.
=> enhance scalar h2d fusion

pytorch_blade/tests/disc/ops/test_layer_norm.py
relate PR: https://github.com/pai-disc/torch-mlir/pull/31
=> [Torch-MLIR] not check assert at runtime

pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/tests/torchscript/basics.graph
CC @tanyokwok @minminsun @wyzero @chenbohua3
=> [Torch-Blade] Erase tuple input shape

pytorch_blade/scripts/pip/requirements-dev-pre+cpu.txt, pytorch_blade/scripts/pip/requirements-dev-pre+cu117.txt, scripts/python/common_setup.py, tao_compiler/mlir/xla/ral/context/stream_executor_based_impl.cc, tensorflow_blade/build.py
Use mkldnn build from source instead of downloaded one.
=> fix mkldnn build

pytorch_blade/pytorch_blade/compiler/mlir/runtime/ral_context.cpp, pytorch_blade/pytorch_blade/compiler/mlir/runtime/ral_context.h, pytorch_blade/tests/disc/test_disc_engine.py
=> Allow change disc engine device after loading.

pytorch_blade/benchmark/TorchBench/requirements_cuda.txt
changed in https://github.com/alibaba/BladeDISC/pull/1145
=> [TorchBench] fix bench dependency

tao_compiler/mlir/disc/transforms/disc_gpu_kernel_to_blob.cc
"export DISC_CUDA_KEEP_TEMPFILES=true" to dump
.ll, .ptx and .cubin for cuda backend.
=> Support to dump cuda ir and binary

examples/PyTorch/Train/Dynamo/StableDiffusion/README.md, examples/PyTorch/Train/Dynamo/StableDiffusion/disc_wrapper.py, examples/PyTorch/Train/Dynamo/StableDiffusion/launch_dreambooth_train.sh, examples/PyTorch/Train/Dynamo/StableDiffusion/train_dreambooth.py, pytorch_blade/pytorch_blade/compiler/jit/torch/shape_analysis.cpp, pytorch_blade/pytorch_blade/torch-mlir/lib/Dialect/TorchConversion/Transforms/DiscDecomposeComplexOps.cpp, pytorch_blade/tests/mhlo/split.mlir, pytorch_blade/tests/torchscript/since_1_14.graph
This PR adds StableDiffusion dreambooth fine-tune job example script and performance number.
=> add stable diffusion fine-tune example

tao_compiler/mlir/disc/disc_compiler.cc, tao_compiler/mlir/disc/transforms/disc_passes.td, tao_compiler/mlir/disc/transforms/fusion_utils.cc, tao_compiler/mlir/disc/transforms/fusion_utils.h, tao_compiler/mlir/disc/transforms/fusion_utils_transform_based.cc, tao_compiler/mlir/disc/transforms/lhlo_fusion.cc, tao_compiler/mlir/disc/transforms/passes.h, tao_compiler/mlir/disc/transforms/tests/cpu-only-lmhlo-fusion.mlir, tao_compiler/mlir/disc/transforms/tests/gpu-only-lhlo-fusion.mlir
Part of the code in https://github.com/alibaba/BladeDISC/pull/1149.
It implements the fusion strategy for the TransformDialect-based GEMM codegen.
=> GPU fusion strategy of TransformDialect-based GEMM codegen.

tao_compiler/mlir/disc/disc_util.cc, tao_compiler/mlir/disc/transforms/disc_duplicate_computation_for_fusion.cc, tao_compiler/mlir/disc/transforms/tests/specialize_fusion_with_speculation.mlir
It has been demonstrated that this feature is robust and effective.
=> Enable the experimental mem-intensive operator optimization by default.
